///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace тпаит
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("cbb1a8c8-592f-4dd9-b1a2-6e4bccd986bd", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the тпаитRepository repository.
        /// </summary>
        public static тпаитRepository repo = тпаитRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'GeoToolsДанныеПоПробе.DBGridData' at 39;74.", repo.GeoToolsДанныеПоПробе.DBGridDataInfo, new RecordItemIndex(0));
            repo.GeoToolsДанныеПоПробе.DBGridData.Click(System.Windows.Forms.MouseButtons.Right, "39;74");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoTools.БазаДанных.MenuItem1' at 43;9.", repo.GeoTools.БазаДанных.MenuItem1Info, new RecordItemIndex(1));
            repo.GeoTools.БазаДанных.MenuItem1.Click("43;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GEOTOOLS1.EdName' at 21;7.", repo.GEOTOOLS1.EdNameInfo, new RecordItemIndex(2));
            repo.GEOTOOLS1.EdName.Click("21;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}{LMenu down}{LShiftKey up}{LMenu up}{LControlKey up}Au' with focus on 'GEOTOOLS1.EdName'.", repo.GEOTOOLS1.EdNameInfo, new RecordItemIndex(3));
            repo.GEOTOOLS1.EdName.PressKeys("{LShiftKey down}{LMenu down}{LShiftKey up}{LMenu up}{LControlKey up}Au");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'GEOTOOLS1.NedMaxContent' at 8;6.", repo.GEOTOOLS1.NedMaxContentInfo, new RecordItemIndex(4));
            repo.GEOTOOLS1.NedMaxContent.MoveTo("8;6");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'GEOTOOLS1.NedMaxContent' at 16;-2.", repo.GEOTOOLS1.NedMaxContentInfo, new RecordItemIndex(5));
            repo.GEOTOOLS1.NedMaxContent.MoveTo("16;-2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'GeoToolsДанныеПоПробе.PanelPalitra.Grid1' at 114;123.", repo.GeoToolsДанныеПоПробе.PanelPalitra.Grid1Info, new RecordItemIndex(6));
            repo.GeoToolsДанныеПоПробе.PanelPalitra.Grid1.MoveTo("114;123");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad9}{NumPad9}' with focus on 'GEOTOOLS1.NedMaxContent'.", repo.GEOTOOLS1.NedMaxContentInfo, new RecordItemIndex(7));
            repo.GEOTOOLS1.NedMaxContent.PressKeys("{NumPad9}{NumPad9}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'GEOTOOLS1.NedMinContent' at 42;6.", repo.GEOTOOLS1.NedMinContentInfo, new RecordItemIndex(8));
            repo.GEOTOOLS1.NedMinContent.MoveTo("42;6");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'GEOTOOLS1.NedMinContent' at 50;-2.", repo.GEOTOOLS1.NedMinContentInfo, new RecordItemIndex(9));
            repo.GEOTOOLS1.NedMinContent.MoveTo("50;-2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'GEOTOOLS1' at 131;164.", repo.GEOTOOLS1.SelfInfo, new RecordItemIndex(10));
            repo.GEOTOOLS1.Self.MoveTo("131;164");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GEOTOOLS1.NedMinContent' at 33;13.", repo.GEOTOOLS1.NedMinContentInfo, new RecordItemIndex(11));
            repo.GEOTOOLS1.NedMinContent.Click("33;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Right}{NumPad1}' with focus on 'GEOTOOLS1.NedMinContent'.", repo.GEOTOOLS1.NedMinContentInfo, new RecordItemIndex(12));
            repo.GEOTOOLS1.NedMinContent.PressKeys("{Right}{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GEOTOOLS1.Применить' at 35;11.", repo.GEOTOOLS1.ПрименитьInfo, new RecordItemIndex(13));
            repo.GEOTOOLS1.Применить.Click("35;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsДанныеПоПробе.PanelPalitra.Добавить' at 40;10.", repo.GeoToolsДанныеПоПробе.PanelPalitra.ДобавитьInfo, new RecordItemIndex(14));
            repo.GeoToolsДанныеПоПробе.PanelPalitra.Добавить.Click("40;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'GeoToolsДанныеПоПробе.PanelPalitra.Cell99000' at 36;12.", repo.GeoToolsДанныеПоПробе.PanelPalitra.Cell99000Info, new RecordItemIndex(15));
            repo.GeoToolsДанныеПоПробе.PanelPalitra.Cell99000.DoubleClick("36;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsДанныеПоПробе.PanelPalitra.Cell99000' at 36;12.", repo.GeoToolsДанныеПоПробе.PanelPalitra.Cell99000Info, new RecordItemIndex(16));
            repo.GeoToolsДанныеПоПробе.PanelPalitra.Cell99000.Click("36;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}'.", new RecordItemIndex(17));
            Keyboard.Press("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsДанныеПоПробе.PanelPalitra.Добавить' at 24;7.", repo.GeoToolsДанныеПоПробе.PanelPalitra.ДобавитьInfo, new RecordItemIndex(18));
            repo.GeoToolsДанныеПоПробе.PanelPalitra.Добавить.Click("24;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'GeoToolsДанныеПоПробе.PanelPalitra.Cell99' at 41;13.", repo.GeoToolsДанныеПоПробе.PanelPalitra.Cell99Info, new RecordItemIndex(19));
            repo.GeoToolsДанныеПоПробе.PanelPalitra.Cell99.DoubleClick("41;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad2}{Right}'.", new RecordItemIndex(20));
            Keyboard.Press("{NumPad2}{Right}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad0}'.", new RecordItemIndex(21));
            Keyboard.Press("{NumPad0}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsДанныеПоПробе.PanelPalitra.Добавить' at 25;16.", repo.GeoToolsДанныеПоПробе.PanelPalitra.ДобавитьInfo, new RecordItemIndex(22));
            repo.GeoToolsДанныеПоПробе.PanelPalitra.Добавить.Click("25;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsДанныеПоПробе.PanelPalitra.Cell99' at 47;2.", repo.GeoToolsДанныеПоПробе.PanelPalitra.Cell99Info, new RecordItemIndex(23));
            repo.GeoToolsДанныеПоПробе.PanelPalitra.Cell99.Click("47;2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad3}{NumPad0}'.", new RecordItemIndex(24));
            Keyboard.Press("{NumPad3}{NumPad0}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsДанныеПоПробе.PanelPalitra.Добавить' at 28;11.", repo.GeoToolsДанныеПоПробе.PanelPalitra.ДобавитьInfo, new RecordItemIndex(25));
            repo.GeoToolsДанныеПоПробе.PanelPalitra.Добавить.Click("28;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad4}{NumPad0}' with focus on 'GeoToolsДанныеПоПробе.PanelPalitra.Добавить'.", repo.GeoToolsДанныеПоПробе.PanelPalitra.ДобавитьInfo, new RecordItemIndex(26));
            repo.GeoToolsДанныеПоПробе.PanelPalitra.Добавить.PressKeys("{NumPad4}{NumPad0}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsДанныеПоПробе.PanelPalitra.Grid1' at 140;133.", repo.GeoToolsДанныеПоПробе.PanelPalitra.Grid1Info, new RecordItemIndex(27));
            repo.GeoToolsДанныеПоПробе.PanelPalitra.Grid1.Click("140;133");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsДанныеПоПробе.PanelPalitra.Grid1' at 190;32.", repo.GeoToolsДанныеПоПробе.PanelPalitra.Grid1Info, new RecordItemIndex(28));
            repo.GeoToolsДанныеПоПробе.PanelPalitra.Grid1.Click("190;32");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Цвет.Text720' at 80;67.", repo.Цвет.Text720Info, new RecordItemIndex(29));
            repo.Цвет.Text720.Click("80;67");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Цвет.ButtonОК' at 57;10.", repo.Цвет.ButtonОКInfo, new RecordItemIndex(30));
            repo.Цвет.ButtonОК.Click("57;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsДанныеПоПробе.PanelPalitra.Grid1' at 191;57.", repo.GeoToolsДанныеПоПробе.PanelPalitra.Grid1Info, new RecordItemIndex(31));
            repo.GeoToolsДанныеПоПробе.PanelPalitra.Grid1.Click("191;57");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Цвет.Text720' at 193;147.", repo.Цвет.Text720Info, new RecordItemIndex(32));
            repo.Цвет.Text720.Click("193;147");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Цвет.ButtonОК' at 68;12.", repo.Цвет.ButtonОКInfo, new RecordItemIndex(33));
            repo.Цвет.ButtonОК.Click("68;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsДанныеПоПробе.PanelPalitra.Grid1' at 189;78.", repo.GeoToolsДанныеПоПробе.PanelPalitra.Grid1Info, new RecordItemIndex(34));
            repo.GeoToolsДанныеПоПробе.PanelPalitra.Grid1.Click("189;78");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Цвет.ButtonОК' at 50;7.", repo.Цвет.ButtonОКInfo, new RecordItemIndex(35));
            repo.Цвет.ButtonОК.Click("50;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsДанныеПоПробе.PanelPalitra.Grid1' at 178;96.", repo.GeoToolsДанныеПоПробе.PanelPalitra.Grid1Info, new RecordItemIndex(36));
            repo.GeoToolsДанныеПоПробе.PanelPalitra.Grid1.Click("178;96");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Цвет.Text720' at 252;90.", repo.Цвет.Text720Info, new RecordItemIndex(37));
            repo.Цвет.Text720.Click("252;90");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Цвет.ButtonОК' at 62;7.", repo.Цвет.ButtonОКInfo, new RecordItemIndex(38));
            repo.Цвет.ButtonОК.Click("62;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsДанныеПоПробе.Закрыть' at 25;7.", repo.GeoToolsДанныеПоПробе.ЗакрытьInfo, new RecordItemIndex(39));
            repo.GeoToolsДанныеПоПробе.Закрыть.Click("25;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GEOTOOLSПримерСкважины.MenuItemБазаДанных' at 69;12.", repo.GEOTOOLSПримерСкважины.MenuItemБазаДанныхInfo, new RecordItemIndex(40));
            repo.GEOTOOLSПримерСкважины.MenuItemБазаДанных.Click("69;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoTools.БазаДанных.MenuItem2' at 67;15.", repo.GeoTools.БазаДанных.MenuItem2Info, new RecordItemIndex(41));
            repo.GeoTools.БазаДанных.MenuItem2.Click("67;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsИмпортДанных.OpenFileBtn' at 14;10.", repo.GeoToolsИмпортДанных.OpenFileBtnInfo, new RecordItemIndex(42));
            repo.GeoToolsИмпортДанных.OpenFileBtn.Click("14;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Открытие.SomeIndicator' at 12;153.", repo.Открытие.SomeIndicatorInfo, new RecordItemIndex(43));
            repo.Открытие.SomeIndicator.MoveTo("12;153");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Открытие.SomeIndicator' at 12;153.", repo.Открытие.SomeIndicatorInfo, new RecordItemIndex(44));
            repo.Открытие.SomeIndicator.MoveTo("12;153");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Открытие.Tree100' at 17;356.", repo.Открытие.Tree100Info, new RecordItemIndex(45));
            repo.Открытие.Tree100.Click("17;356");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Открытие.Tree100' at 26;294.", repo.Открытие.Tree100Info, new RecordItemIndex(46));
            repo.Открытие.Tree100.Click("26;294");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Открытие.Tree100' at 32;283.", repo.Открытие.Tree100Info, new RecordItemIndex(47));
            repo.Открытие.Tree100.Click("32;283");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Открытие.Tree100' at 43;285.", repo.Открытие.Tree100Info, new RecordItemIndex(48));
            repo.Открытие.Tree100.Click("43;285");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -120 units.", new RecordItemIndex(49));
            Mouse.ScrollWheel(-120);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Открытие.Tree100' at 76;286.", repo.Открытие.Tree100Info, new RecordItemIndex(50));
            repo.Открытие.Tree100.Click("76;286");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Открытие.Открытие' at 615;29.", repo.Открытие.ОткрытиеInfo, new RecordItemIndex(51));
            repo.Открытие.Открытие.MoveTo("615;29");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Открытие.Открытие' at 637;-141.", repo.Открытие.ОткрытиеInfo, new RecordItemIndex(52));
            repo.Открытие.Открытие.MoveTo("637;-141");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Открытие.ComboBox1136' at 64;12.", repo.Открытие.ComboBox1136Info, new RecordItemIndex(53));
            repo.Открытие.ComboBox1136.Click("64;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.ФайлыMSExcelAsteriskXlsAsteriskX' at 78;6.", repo.List1000.ФайлыMSExcelAsteriskXlsAsteriskXInfo, new RecordItemIndex(54));
            repo.List1000.ФайлыMSExcelAsteriskXlsAsteriskX.Click("78;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Открытие.SystemItemNameDisplay' at 44;14.", repo.Открытие.SystemItemNameDisplayInfo, new RecordItemIndex(55));
            repo.Открытие.SystemItemNameDisplay.Click("44;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Открытие.ButtonОткрыть' at 25;16.", repo.Открытие.ButtonОткрытьInfo, new RecordItemIndex(56));
            repo.Открытие.ButtonОткрыть.Click("25;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'МастерИмпортаШаг1Из1.SomeButton' at 10;4.", repo.МастерИмпортаШаг1Из1.SomeButtonInfo, new RecordItemIndex(57));
            repo.МастерИмпортаШаг1Из1.SomeButton.Click("10;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.СквУстья' at 65;6.", repo.List1000.СквУстьяInfo, new RecordItemIndex(58));
            repo.List1000.СквУстья.Click("65;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'МастерИмпортаШаг1Из1.RazdNum' at 29;7.", repo.МастерИмпортаШаг1Из1.RazdNumInfo, new RecordItemIndex(59));
            repo.МастерИмпортаШаг1Из1.RazdNum.MoveTo("29;7");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'МастерИмпортаШаг1Из1.RazdNum' at 37;-1.", repo.МастерИмпортаШаг1Из1.RazdNumInfo, new RecordItemIndex(60));
            repo.МастерИмпортаШаг1Из1.RazdNum.MoveTo("37;-1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'МастерИмпортаШаг1Из1.ListNBox' at 108;15.", repo.МастерИмпортаШаг1Из1.ListNBoxInfo, new RecordItemIndex(61));
            repo.МастерИмпортаШаг1Из1.ListNBox.MoveTo("108;15");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad2}' with focus on 'МастерИмпортаШаг1Из1.RazdNum'.", repo.МастерИмпортаШаг1Из1.RazdNumInfo, new RecordItemIndex(62));
            repo.МастерИмпортаШаг1Из1.RazdNum.PressKeys("{NumPad2}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'МастерИмпортаШаг1Из1.TitleInd' at 27;12.", repo.МастерИмпортаШаг1Из1.TitleIndInfo, new RecordItemIndex(63));
            repo.МастерИмпортаШаг1Из1.TitleInd.MoveTo("27;12");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'МастерИмпортаШаг1Из1.TitleInd' at 35;4.", repo.МастерИмпортаШаг1Из1.TitleIndInfo, new RecordItemIndex(64));
            repo.МастерИмпортаШаг1Из1.TitleInd.MoveTo("35;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'GEOTOOLSПримерСкважины.PageControl1' at 539;372.", repo.GEOTOOLSПримерСкважины.PageControl1Info, new RecordItemIndex(65));
            repo.GEOTOOLSПримерСкважины.PageControl1.MoveTo("539;372");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'МастерИмпортаШаг1Из1.TitleInd'.", repo.МастерИмпортаШаг1Из1.TitleIndInfo, new RecordItemIndex(66));
            repo.МастерИмпортаШаг1Из1.TitleInd.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'МастерИмпортаШаг1Из1.Готово' at 39;5.", repo.МастерИмпортаШаг1Из1.ГотовоInfo, new RecordItemIndex(67));
            repo.МастерИмпортаШаг1Из1.Готово.Click("39;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsИмпортДанных.SomeButton' at 5;6.", repo.GeoToolsИмпортДанных.SomeButtonInfo, new RecordItemIndex(68));
            repo.GeoToolsИмпортДанных.SomeButton.Click("5;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.Скважины' at 91;7.", repo.List1000.СкважиныInfo, new RecordItemIndex(69));
            repo.List1000.Скважины.Click("91;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'GeoToolsИмпортДанных.PoleNameGr' at 196;24.", repo.GeoToolsИмпортДанных.PoleNameGrInfo, new RecordItemIndex(70));
            repo.GeoToolsИмпортДанных.PoleNameGr.MoveTo("196;24");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'GeoToolsИмпортДанных.PoleNameGr' at 204;16.", repo.GeoToolsИмпортДанных.PoleNameGrInfo, new RecordItemIndex(71));
            repo.GeoToolsИмпортДанных.PoleNameGr.MoveTo("204;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'GeoToolsИмпортДанных.ListNameGr' at 149;27.", repo.GeoToolsИмпортДанных.ListNameGrInfo, new RecordItemIndex(72));
            repo.GeoToolsИмпортДанных.ListNameGr.MoveTo("149;27");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsИмпортДанных.PoleNameGr1.CellX' at 78;5.", repo.GeoToolsИмпортДанных.PoleNameGr1.CellXInfo, new RecordItemIndex(73));
            repo.GeoToolsИмпортДанных.PoleNameGr1.CellX.Click("78;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'GeoToolsИмпортДанных.Down' at 10;9.", repo.GeoToolsИмпортДанных.DownInfo, new RecordItemIndex(74));
            repo.GeoToolsИмпортДанных.Down.DoubleClick("10;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsИмпортДанных.Down' at 10;9.", repo.GeoToolsИмпортДанных.DownInfo, new RecordItemIndex(75));
            repo.GeoToolsИмпортДанных.Down.Click("10;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsИмпортДанных.PoleNameGr1.Down1' at 6;8.", repo.GeoToolsИмпортДанных.PoleNameGr1.Down1Info, new RecordItemIndex(76));
            repo.GeoToolsИмпортДанных.PoleNameGr1.Down1.Click("6;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsИмпортДанных.PoleNameGr1.Down1' at 6;8.", repo.GeoToolsИмпортДанных.PoleNameGr1.Down1Info, new RecordItemIndex(77));
            repo.GeoToolsИмпортДанных.PoleNameGr1.Down1.Click("6;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsИмпортДанных.PoleNameGr1.Down1' at 6;8.", repo.GeoToolsИмпортДанных.PoleNameGr1.Down1Info, new RecordItemIndex(78));
            repo.GeoToolsИмпортДанных.PoleNameGr1.Down1.Click("6;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsИмпортДанных.PoleNameGr1.Down1' at 6;8.", repo.GeoToolsИмпортДанных.PoleNameGr1.Down1Info, new RecordItemIndex(79));
            repo.GeoToolsИмпортДанных.PoleNameGr1.Down1.Click("6;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsИмпортДанных.ButtonUp' at 12;10.", repo.GeoToolsИмпортДанных.ButtonUpInfo, new RecordItemIndex(80));
            repo.GeoToolsИмпортДанных.ButtonUp.Click("12;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsИмпортДанных.ButtonUp' at 12;10.", repo.GeoToolsИмпортДанных.ButtonUpInfo, new RecordItemIndex(81));
            repo.GeoToolsИмпортДанных.ButtonUp.Click("12;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsИмпортДанных.ListNameGr' at 121;50.", repo.GeoToolsИмпортДанных.ListNameGrInfo, new RecordItemIndex(82));
            repo.GeoToolsИмпортДанных.ListNameGr.Click("121;50");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsИмпортДанных.PoleNameGr1.PLine' at 64;12.", repo.GeoToolsИмпортДанных.PoleNameGr1.PLineInfo, new RecordItemIndex(83));
            repo.GeoToolsИмпортДанных.PoleNameGr1.PLine.Click("64;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsИмпортДанных.CopyNameBtn' at 20;5.", repo.GeoToolsИмпортДанных.CopyNameBtnInfo, new RecordItemIndex(84));
            repo.GeoToolsИмпортДанных.CopyNameBtn.Click("20;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 960 units.", new RecordItemIndex(85));
            Mouse.ScrollWheel(960);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -720 units.", new RecordItemIndex(86));
            Mouse.ScrollWheel(-720);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsИмпортДанных.Импорт' at 52;13.", repo.GeoToolsИмпортДанных.ИмпортInfo, new RecordItemIndex(87));
            repo.GeoToolsИмпортДанных.Импорт.Click("52;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Подтверждение.ButtonДа' at 44;17.", repo.Подтверждение.ButtonДаInfo, new RecordItemIndex(88));
            repo.Подтверждение.ButtonДа.Click("44;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Информация.ButtonОК' at 40;14.", repo.Информация.ButtonОКInfo, new RecordItemIndex(89));
            repo.Информация.ButtonОК.Click("40;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsИмпортДанных.ListNameGr' at 108;77.", repo.GeoToolsИмпортДанных.ListNameGrInfo, new RecordItemIndex(90));
            repo.GeoToolsИмпортДанных.ListNameGr.Click("108;77");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -4440 units.", new RecordItemIndex(91));
            Mouse.ScrollWheel(-4440);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsИмпортДанных.OpenFileBtn' at 12;10.", repo.GeoToolsИмпортДанных.OpenFileBtnInfo, new RecordItemIndex(92));
            repo.GeoToolsИмпортДанных.OpenFileBtn.Click("12;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Открытие.SystemItemNameDisplay1' at 31;15.", repo.Открытие.SystemItemNameDisplay1Info, new RecordItemIndex(93));
            repo.Открытие.SystemItemNameDisplay1.Click("31;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Открытие.ButtonОткрыть' at 81;13.", repo.Открытие.ButtonОткрытьInfo, new RecordItemIndex(94));
            repo.Открытие.ButtonОткрыть.Click("81;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsИмпортДанных.SomeButton' at 13;7.", repo.GeoToolsИмпортДанных.SomeButtonInfo, new RecordItemIndex(95));
            repo.GeoToolsИмпортДанных.SomeButton.Click("13;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ошибка.ButtonОК' at 33;22.", repo.Ошибка.ButtonОКInfo, new RecordItemIndex(96));
            repo.Ошибка.ButtonОК.Click("33;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsИмпортДанных.Bevel2' at 525;1.", repo.GeoToolsИмпортДанных.Bevel2Info, new RecordItemIndex(97));
            repo.GeoToolsИмпортДанных.Bevel2.Click("525;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsИмпортДанных.Закрыть' at 27;12.", repo.GeoToolsИмпортДанных.ЗакрытьInfo, new RecordItemIndex(98));
            repo.GeoToolsИмпортДанных.Закрыть.Click("27;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GEOTOOLSПримерСкважины.MenuItemБазаДанных' at 46;5.", repo.GEOTOOLSПримерСкважины.MenuItemБазаДанныхInfo, new RecordItemIndex(99));
            repo.GEOTOOLSПримерСкважины.MenuItemБазаДанных.Click("46;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoTools.БазаДанных.MenuItem2' at 88;19.", repo.GeoTools.БазаДанных.MenuItem2Info, new RecordItemIndex(100));
            repo.GeoTools.БазаДанных.MenuItem2.Click("88;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Ошибка.ButtonОК' at 64;11.", repo.Ошибка.ButtonОКInfo, new RecordItemIndex(101));
            repo.Ошибка.ButtonОК.Click("64;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsИмпортДанных.SomeButton' at 4;13.", repo.GeoToolsИмпортДанных.SomeButtonInfo, new RecordItemIndex(102));
            repo.GeoToolsИмпортДанных.SomeButton.Click("4;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.ПробыСкважины' at 41;9.", repo.List1000.ПробыСкважиныInfo, new RecordItemIndex(103));
            repo.List1000.ПробыСкважины.Click("41;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsИмпортДанных.OpenFileBtn' at 12;13.", repo.GeoToolsИмпортДанных.OpenFileBtnInfo, new RecordItemIndex(104));
            repo.GeoToolsИмпортДанных.OpenFileBtn.Click("12;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Открытие.SystemItemNameDisplay' at 18;13.", repo.Открытие.SystemItemNameDisplayInfo, new RecordItemIndex(105));
            repo.Открытие.SystemItemNameDisplay.DoubleClick("18;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'МастерИмпортаШаг1Из1.ListNBox' at 111;6.", repo.МастерИмпортаШаг1Из1.ListNBoxInfo, new RecordItemIndex(106));
            repo.МастерИмпортаШаг1Из1.ListNBox.Click("111;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.СквОпроб' at 73;7.", repo.List1000.СквОпробInfo, new RecordItemIndex(107));
            repo.List1000.СквОпроб.Click("73;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'МастерИмпортаШаг1Из1.Готово' at 45;13.", repo.МастерИмпортаШаг1Из1.ГотовоInfo, new RecordItemIndex(108));
            repo.МастерИмпортаШаг1Из1.Готово.Click("45;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsИмпортДанных.AllPoleCopBtn' at 11;9.", repo.GeoToolsИмпортДанных.AllPoleCopBtnInfo, new RecordItemIndex(109));
            repo.GeoToolsИмпортДанных.AllPoleCopBtn.Click("11;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsИмпортДанных.Импорт' at 42;9.", repo.GeoToolsИмпортДанных.ИмпортInfo, new RecordItemIndex(110));
            repo.GeoToolsИмпортДанных.Импорт.Click("42;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Информация.ButtonОК' at 30;9.", repo.Информация.ButtonОКInfo, new RecordItemIndex(111));
            repo.Информация.ButtonОК.Click("30;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoToolsИмпортДанных.Закрыть' at 30;13.", repo.GeoToolsИмпортДанных.ЗакрытьInfo, new RecordItemIndex(112));
            repo.GeoToolsИмпортДанных.Закрыть.Click("30;13");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
