///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace тпаит
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The try recording.
    /// </summary>
    [TestModule("dde40a90-cf85-4539-9934-b4dd9ee04150", ModuleType.Recording, 1)]
    public partial class @try : ITestModule
    {
        /// <summary>
        /// Holds an instance of the тпаитRepository repository.
        /// </summary>
        public static тпаитRepository repo = тпаитRepository.Instance;

        static @try instance = new @try();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public @try()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static @try Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Program Files (x86)\\Mineframe 7.0\\bin\\GeoTools.exe' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Program Files (x86)\\Mineframe 7.0\\bin\\GeoTools.exe", "", "C:\\Program Files (x86)\\Mineframe 7.0\\bin", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GEOTOOLSПримерСкважины.MenuItemБазаДанных' at 43;14.", repo.GEOTOOLSПримерСкважины.MenuItemБазаДанныхInfo, new RecordItemIndex(1));
            repo.GEOTOOLSПримерСкважины.MenuItemБазаДанных.Click("43;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoTools.БазаДанных.MenuItem' at 49;17.", repo.GeoTools.БазаДанных.MenuItemInfo, new RecordItemIndex(2));
            repo.GeoTools.БазаДанных.MenuItem.Click("49;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GEOTOOLSНастройки.Применить' at 29;20.", repo.GEOTOOLSНастройки.ПрименитьInfo, new RecordItemIndex(3));
            repo.GEOTOOLSНастройки.Применить.Click("29;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GEOTOOLSПримерСкважины.MenuItemБазаДанных' at 71;7.", repo.GEOTOOLSПримерСкважины.MenuItemБазаДанныхInfo, new RecordItemIndex(4));
            repo.GEOTOOLSПримерСкважины.MenuItemБазаДанных.Click("71;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoTools.БазаДанных.MenuItem1' at 86;20.", repo.GeoTools.БазаДанных.MenuItem1Info, new RecordItemIndex(5));
            repo.GeoTools.БазаДанных.MenuItem1.Click("86;20");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
