///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace тпаит
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the тпаитRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("38c41790-e863-47c3-8fee-9a2305865b88")]
    public partial class тпаитRepository : RepoGenBaseFolder
    {
        static тпаитRepository instance = new тпаитRepository();
        тпаитRepositoryFolders.GEOTOOLSПримерСкважиныAppFolder _geotoolsпримерскважины;
        тпаитRepositoryFolders.GeoToolsAppFolder _geotools;
        тпаитRepositoryFolders.GEOTOOLSНастройкиAppFolder _geotoolsнастройки;
        тпаитRepositoryFolders.GeoToolsДанныеПоПробеAppFolder _geotoolsданныепопробе;
        тпаитRepositoryFolders.GEOTOOLS1AppFolder _geotools1;
        тпаитRepositoryFolders.ЦветAppFolder _цвет;
        тпаитRepositoryFolders.GeoToolsИмпортДанныхAppFolder _geotoolsимпортданных;
        тпаитRepositoryFolders.ОткрытиеAppFolder _открытие;
        тпаитRepositoryFolders.List1000AppFolder _list1000;
        тпаитRepositoryFolders.МастерИмпортаШаг1Из1AppFolder _мастеримпорташаг1из1;
        тпаитRepositoryFolders.ПодтверждениеAppFolder _подтверждение;
        тпаитRepositoryFolders.ИнформацияAppFolder _информация;
        тпаитRepositoryFolders.ОшибкаAppFolder _ошибка;

        /// <summary>
        /// Gets the singleton class instance representing the тпаитRepository element repository.
        /// </summary>
        [RepositoryFolder("38c41790-e863-47c3-8fee-9a2305865b88")]
        public static тпаитRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public тпаитRepository() 
            : base("тпаитRepository", "/", null, 0, false, "38c41790-e863-47c3-8fee-9a2305865b88", ".\\RepositoryImages\\тпаитRepository38c41790.rximgres")
        {
            _geotoolsпримерскважины = new тпаитRepositoryFolders.GEOTOOLSПримерСкважиныAppFolder(this);
            _geotools = new тпаитRepositoryFolders.GeoToolsAppFolder(this);
            _geotoolsнастройки = new тпаитRepositoryFolders.GEOTOOLSНастройкиAppFolder(this);
            _geotoolsданныепопробе = new тпаитRepositoryFolders.GeoToolsДанныеПоПробеAppFolder(this);
            _geotools1 = new тпаитRepositoryFolders.GEOTOOLS1AppFolder(this);
            _цвет = new тпаитRepositoryFolders.ЦветAppFolder(this);
            _geotoolsимпортданных = new тпаитRepositoryFolders.GeoToolsИмпортДанныхAppFolder(this);
            _открытие = new тпаитRepositoryFolders.ОткрытиеAppFolder(this);
            _list1000 = new тпаитRepositoryFolders.List1000AppFolder(this);
            _мастеримпорташаг1из1 = new тпаитRepositoryFolders.МастерИмпортаШаг1Из1AppFolder(this);
            _подтверждение = new тпаитRepositoryFolders.ПодтверждениеAppFolder(this);
            _информация = new тпаитRepositoryFolders.ИнформацияAppFolder(this);
            _ошибка = new тпаитRepositoryFolders.ОшибкаAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("38c41790-e863-47c3-8fee-9a2305865b88")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The GEOTOOLSПримерСкважины folder.
        /// </summary>
        [RepositoryFolder("1e8303a0-4d66-4820-9d59-24c69fa4034c")]
        public virtual тпаитRepositoryFolders.GEOTOOLSПримерСкважиныAppFolder GEOTOOLSПримерСкважины
        {
            get { return _geotoolsпримерскважины; }
        }

        /// <summary>
        /// The GeoTools folder.
        /// </summary>
        [RepositoryFolder("707811b5-b95f-4138-9395-671c2887dc06")]
        public virtual тпаитRepositoryFolders.GeoToolsAppFolder GeoTools
        {
            get { return _geotools; }
        }

        /// <summary>
        /// The GEOTOOLSНастройки folder.
        /// </summary>
        [RepositoryFolder("1f130b67-3801-4584-853d-c2266d2442db")]
        public virtual тпаитRepositoryFolders.GEOTOOLSНастройкиAppFolder GEOTOOLSНастройки
        {
            get { return _geotoolsнастройки; }
        }

        /// <summary>
        /// The GeoToolsДанныеПоПробе folder.
        /// </summary>
        [RepositoryFolder("aac82a23-b610-4be0-8d03-2d23b66fc3f7")]
        public virtual тпаитRepositoryFolders.GeoToolsДанныеПоПробеAppFolder GeoToolsДанныеПоПробе
        {
            get { return _geotoolsданныепопробе; }
        }

        /// <summary>
        /// The GEOTOOLS1 folder.
        /// </summary>
        [RepositoryFolder("dea7cdfa-e2dc-4b32-8251-b3c5101d03a6")]
        public virtual тпаитRepositoryFolders.GEOTOOLS1AppFolder GEOTOOLS1
        {
            get { return _geotools1; }
        }

        /// <summary>
        /// The Цвет folder.
        /// </summary>
        [RepositoryFolder("73e8a368-e784-4b98-b546-d9ce3ddeff9e")]
        public virtual тпаитRepositoryFolders.ЦветAppFolder Цвет
        {
            get { return _цвет; }
        }

        /// <summary>
        /// The GeoToolsИмпортДанных folder.
        /// </summary>
        [RepositoryFolder("f693525c-c24f-458f-8364-181cea85952a")]
        public virtual тпаитRepositoryFolders.GeoToolsИмпортДанныхAppFolder GeoToolsИмпортДанных
        {
            get { return _geotoolsимпортданных; }
        }

        /// <summary>
        /// The Открытие folder.
        /// </summary>
        [RepositoryFolder("a0549ae5-1e19-458b-90e5-1b322d0a130f")]
        public virtual тпаитRepositoryFolders.ОткрытиеAppFolder Открытие
        {
            get { return _открытие; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("d5e97338-7963-4ea0-a3fb-03facc94dbb5")]
        public virtual тпаитRepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }

        /// <summary>
        /// The МастерИмпортаШаг1Из1 folder.
        /// </summary>
        [RepositoryFolder("fda58a26-8107-4047-a116-8022caa7a130")]
        public virtual тпаитRepositoryFolders.МастерИмпортаШаг1Из1AppFolder МастерИмпортаШаг1Из1
        {
            get { return _мастеримпорташаг1из1; }
        }

        /// <summary>
        /// The Подтверждение folder.
        /// </summary>
        [RepositoryFolder("5f8e2632-4b1b-413d-8d82-41cf21c3f26a")]
        public virtual тпаитRepositoryFolders.ПодтверждениеAppFolder Подтверждение
        {
            get { return _подтверждение; }
        }

        /// <summary>
        /// The Информация folder.
        /// </summary>
        [RepositoryFolder("d6f1efc0-7a57-4541-8c79-d67c47c7b91f")]
        public virtual тпаитRepositoryFolders.ИнформацияAppFolder Информация
        {
            get { return _информация; }
        }

        /// <summary>
        /// The Ошибка folder.
        /// </summary>
        [RepositoryFolder("dc261375-95a6-4162-a3ee-bb6b0f4b720e")]
        public virtual тпаитRepositoryFolders.ОшибкаAppFolder Ошибка
        {
            get { return _ошибка; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class тпаитRepositoryFolders
    {
        /// <summary>
        /// The GEOTOOLSПримерСкважиныAppFolder folder.
        /// </summary>
        [RepositoryFolder("1e8303a0-4d66-4820-9d59-24c69fa4034c")]
        public partial class GEOTOOLSПримерСкважиныAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _menuitemбазаданныхInfo;
            RepoItemInfo _pagecontrol1Info;

            /// <summary>
            /// Creates a new GEOTOOLSПримерСкважины  folder.
            /// </summary>
            public GEOTOOLSПримерСкважиныAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GEOTOOLSПримерСкважины", "/form[@name='MainForm' and @title~'^GEOTOOLS\\ -\\ \\[Пример]\\ -\\ \\[Ск']", parentFolder, 30000, null, true, "1e8303a0-4d66-4820-9d59-24c69fa4034c", "")
            {
                _menuitemбазаданныхInfo = new RepoItemInfo(this, "MenuItemБазаДанных", "?/?/menuitem[@name='mmFile']", 30000, null, "f8443ff0-0329-42e4-bf44-af2b0057d530");
                _pagecontrol1Info = new RepoItemInfo(this, "PageControl1", "?/?/tabpagelist[@name='PageControl1']", 30000, null, "d7a475a7-c585-438f-b576-781af36f4442");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1e8303a0-4d66-4820-9d59-24c69fa4034c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1e8303a0-4d66-4820-9d59-24c69fa4034c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenuItemБазаДанных item.
            /// </summary>
            [RepositoryItem("f8443ff0-0329-42e4-bf44-af2b0057d530")]
            public virtual Ranorex.MenuItem MenuItemБазаДанных
            {
                get
                {
                    return _menuitemбазаданныхInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemБазаДанных item info.
            /// </summary>
            [RepositoryItemInfo("f8443ff0-0329-42e4-bf44-af2b0057d530")]
            public virtual RepoItemInfo MenuItemБазаДанныхInfo
            {
                get
                {
                    return _menuitemбазаданныхInfo;
                }
            }

            /// <summary>
            /// The PageControl1 item.
            /// </summary>
            [RepositoryItem("d7a475a7-c585-438f-b576-781af36f4442")]
            public virtual Ranorex.TabPageList PageControl1
            {
                get
                {
                    return _pagecontrol1Info.CreateAdapter<Ranorex.TabPageList>(true);
                }
            }

            /// <summary>
            /// The PageControl1 item info.
            /// </summary>
            [RepositoryItemInfo("d7a475a7-c585-438f-b576-781af36f4442")]
            public virtual RepoItemInfo PageControl1Info
            {
                get
                {
                    return _pagecontrol1Info;
                }
            }
        }

        /// <summary>
        /// The GeoToolsAppFolder folder.
        /// </summary>
        [RepositoryFolder("707811b5-b95f-4138-9395-671c2887dc06")]
        public partial class GeoToolsAppFolder : RepoGenBaseFolder
        {
            тпаитRepositoryFolders.БазаДанныхFolder _базаданных;

            /// <summary>
            /// Creates a new GeoTools  folder.
            /// </summary>
            public GeoToolsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GeoTools", "/contextmenu[@processname='GeoTools']", parentFolder, 30000, null, false, "707811b5-b95f-4138-9395-671c2887dc06", "")
            {
                _базаданных = new тпаитRepositoryFolders.БазаДанныхFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("707811b5-b95f-4138-9395-671c2887dc06")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("707811b5-b95f-4138-9395-671c2887dc06")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The БазаДанных folder.
            /// </summary>
            [RepositoryFolder("9a9f92a2-d358-46c2-94dd-280da2bbf7ae")]
            public virtual тпаитRepositoryFolders.БазаДанныхFolder БазаДанных
            {
                get { return _базаданных; }
            }
        }

        /// <summary>
        /// The БазаДанныхFolder folder.
        /// </summary>
        [RepositoryFolder("9a9f92a2-d358-46c2-94dd-280da2bbf7ae")]
        public partial class БазаДанныхFolder : RepoGenBaseFolder
        {
            RepoItemInfo _menuitemInfo;
            RepoItemInfo _menuitem1Info;
            RepoItemInfo _menuitem2Info;

            /// <summary>
            /// Creates a new БазаДанных  folder.
            /// </summary>
            public БазаДанныхFolder(RepoGenBaseFolder parentFolder) :
                    base("БазаДанных", "contextmenu", parentFolder, 30000, null, false, "9a9f92a2-d358-46c2-94dd-280da2bbf7ae", "")
            {
                _menuitemInfo = new RepoItemInfo(this, "MenuItem", "menuitem[1]", 30000, null, "92ed09a3-5643-4e61-86d6-e323c11faf15");
                _menuitem1Info = new RepoItemInfo(this, "MenuItem1", "menuitem[4]", 30000, null, "fef51030-fe4b-4841-977c-2c67759f3528");
                _menuitem2Info = new RepoItemInfo(this, "MenuItem2", "menuitem[6]", 30000, null, "e1ba6531-85c4-49d8-88b1-3415b6a16453");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9a9f92a2-d358-46c2-94dd-280da2bbf7ae")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9a9f92a2-d358-46c2-94dd-280da2bbf7ae")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenuItem item.
            /// </summary>
            [RepositoryItem("92ed09a3-5643-4e61-86d6-e323c11faf15")]
            public virtual Ranorex.MenuItem MenuItem
            {
                get
                {
                    return _menuitemInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItem item info.
            /// </summary>
            [RepositoryItemInfo("92ed09a3-5643-4e61-86d6-e323c11faf15")]
            public virtual RepoItemInfo MenuItemInfo
            {
                get
                {
                    return _menuitemInfo;
                }
            }

            /// <summary>
            /// The MenuItem1 item.
            /// </summary>
            [RepositoryItem("fef51030-fe4b-4841-977c-2c67759f3528")]
            public virtual Ranorex.MenuItem MenuItem1
            {
                get
                {
                    return _menuitem1Info.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItem1 item info.
            /// </summary>
            [RepositoryItemInfo("fef51030-fe4b-4841-977c-2c67759f3528")]
            public virtual RepoItemInfo MenuItem1Info
            {
                get
                {
                    return _menuitem1Info;
                }
            }

            /// <summary>
            /// The MenuItem2 item.
            /// </summary>
            [RepositoryItem("e1ba6531-85c4-49d8-88b1-3415b6a16453")]
            public virtual Ranorex.MenuItem MenuItem2
            {
                get
                {
                    return _menuitem2Info.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItem2 item info.
            /// </summary>
            [RepositoryItemInfo("e1ba6531-85c4-49d8-88b1-3415b6a16453")]
            public virtual RepoItemInfo MenuItem2Info
            {
                get
                {
                    return _menuitem2Info;
                }
            }
        }

        /// <summary>
        /// The GEOTOOLSНастройкиAppFolder folder.
        /// </summary>
        [RepositoryFolder("1f130b67-3801-4584-853d-c2266d2442db")]
        public partial class GEOTOOLSНастройкиAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _применитьInfo;

            /// <summary>
            /// Creates a new GEOTOOLSНастройки  folder.
            /// </summary>
            public GEOTOOLSНастройкиAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GEOTOOLSНастройки", "/form[@name='frmSettings']", parentFolder, 30000, null, true, "1f130b67-3801-4584-853d-c2266d2442db", "")
            {
                _применитьInfo = new RepoItemInfo(this, "Применить", "button[@name='btnApply']", 30000, null, "c7f62886-fc14-4f66-a35f-e516ba075f0a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1f130b67-3801-4584-853d-c2266d2442db")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1f130b67-3801-4584-853d-c2266d2442db")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Применить item.
            /// </summary>
            [RepositoryItem("c7f62886-fc14-4f66-a35f-e516ba075f0a")]
            public virtual Ranorex.Button Применить
            {
                get
                {
                    return _применитьInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Применить item info.
            /// </summary>
            [RepositoryItemInfo("c7f62886-fc14-4f66-a35f-e516ba075f0a")]
            public virtual RepoItemInfo ПрименитьInfo
            {
                get
                {
                    return _применитьInfo;
                }
            }
        }

        /// <summary>
        /// The GeoToolsДанныеПоПробеAppFolder folder.
        /// </summary>
        [RepositoryFolder("aac82a23-b610-4be0-8d03-2d23b66fc3f7")]
        public partial class GeoToolsДанныеПоПробеAppFolder : RepoGenBaseFolder
        {
            тпаитRepositoryFolders.PanelPalitraFolder _panelpalitra;
            RepoItemInfo _dbgriddataInfo;
            RepoItemInfo _закрытьInfo;

            /// <summary>
            /// Creates a new GeoToolsДанныеПоПробе  folder.
            /// </summary>
            public GeoToolsДанныеПоПробеAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GeoToolsДанныеПоПробе", "/form[@name='AddStringsForm']", parentFolder, 30000, null, true, "aac82a23-b610-4be0-8d03-2d23b66fc3f7", "")
            {
                _panelpalitra = new тпаитRepositoryFolders.PanelPalitraFolder(this);
                _dbgriddataInfo = new RepoItemInfo(this, "DBGridData", "?/?/container[@name='tshKomp']/?/?/table[@name='DBGridData']", 30000, null, "21d71ec1-fde1-4af6-a12c-53749dafab8b");
                _закрытьInfo = new RepoItemInfo(this, "Закрыть", "?/?/container[@name='tshKomp']/?/?/button[@name='bbClose']", 30000, null, "b8c2d1a3-fa94-47a2-b880-2b9c62628234");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("aac82a23-b610-4be0-8d03-2d23b66fc3f7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("aac82a23-b610-4be0-8d03-2d23b66fc3f7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DBGridData item.
            /// </summary>
            [RepositoryItem("21d71ec1-fde1-4af6-a12c-53749dafab8b")]
            public virtual Ranorex.Table DBGridData
            {
                get
                {
                    return _dbgriddataInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The DBGridData item info.
            /// </summary>
            [RepositoryItemInfo("21d71ec1-fde1-4af6-a12c-53749dafab8b")]
            public virtual RepoItemInfo DBGridDataInfo
            {
                get
                {
                    return _dbgriddataInfo;
                }
            }

            /// <summary>
            /// The Закрыть item.
            /// </summary>
            [RepositoryItem("b8c2d1a3-fa94-47a2-b880-2b9c62628234")]
            public virtual Ranorex.Button Закрыть
            {
                get
                {
                    return _закрытьInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Закрыть item info.
            /// </summary>
            [RepositoryItemInfo("b8c2d1a3-fa94-47a2-b880-2b9c62628234")]
            public virtual RepoItemInfo ЗакрытьInfo
            {
                get
                {
                    return _закрытьInfo;
                }
            }

            /// <summary>
            /// The PanelPalitra folder.
            /// </summary>
            [RepositoryFolder("3b4b24da-d107-4a16-980b-1ccae74440f3")]
            public virtual тпаитRepositoryFolders.PanelPalitraFolder PanelPalitra
            {
                get { return _panelpalitra; }
            }
        }

        /// <summary>
        /// The PanelPalitraFolder folder.
        /// </summary>
        [RepositoryFolder("3b4b24da-d107-4a16-980b-1ccae74440f3")]
        public partial class PanelPalitraFolder : RepoGenBaseFolder
        {
            RepoItemInfo _добавитьInfo;
            RepoItemInfo _grid1Info;
            RepoItemInfo _cell99Info;
            RepoItemInfo _cell99000Info;

            /// <summary>
            /// Creates a new PanelPalitra  folder.
            /// </summary>
            public PanelPalitraFolder(RepoGenBaseFolder parentFolder) :
                    base("PanelPalitra", "?/?/container[@name='PanelPalitra']", parentFolder, 30000, null, false, "3b4b24da-d107-4a16-980b-1ccae74440f3", "")
            {
                _добавитьInfo = new RepoItemInfo(this, "Добавить", "?/?/button[@name='AddSpBut']", 30000, null, "14aa631b-1b3d-4508-b84c-25b51fe5e217");
                _grid1Info = new RepoItemInfo(this, "Grid1", "table[@name='Grid1']", 30000, null, "5505bff5-1027-498b-b699-a95c0b133a10");
                _cell99Info = new RepoItemInfo(this, "Cell99", "table[@name='Grid1']/?/?/cell[@name='99']", 30000, null, "060b7b7d-8350-4691-bfdf-5d1327b0d19f");
                _cell99000Info = new RepoItemInfo(this, "Cell99000", "table[@name='Grid1']/?/?/cell[@name='99.000']", 30000, null, "311f5664-708f-464d-b83d-4f5d05a9b1cc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3b4b24da-d107-4a16-980b-1ccae74440f3")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3b4b24da-d107-4a16-980b-1ccae74440f3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Добавить item.
            /// </summary>
            [RepositoryItem("14aa631b-1b3d-4508-b84c-25b51fe5e217")]
            public virtual Ranorex.Button Добавить
            {
                get
                {
                    return _добавитьInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Добавить item info.
            /// </summary>
            [RepositoryItemInfo("14aa631b-1b3d-4508-b84c-25b51fe5e217")]
            public virtual RepoItemInfo ДобавитьInfo
            {
                get
                {
                    return _добавитьInfo;
                }
            }

            /// <summary>
            /// The Grid1 item.
            /// </summary>
            [RepositoryItem("5505bff5-1027-498b-b699-a95c0b133a10")]
            public virtual Ranorex.Table Grid1
            {
                get
                {
                    return _grid1Info.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Grid1 item info.
            /// </summary>
            [RepositoryItemInfo("5505bff5-1027-498b-b699-a95c0b133a10")]
            public virtual RepoItemInfo Grid1Info
            {
                get
                {
                    return _grid1Info;
                }
            }

            /// <summary>
            /// The Cell99 item.
            /// </summary>
            [RepositoryItem("060b7b7d-8350-4691-bfdf-5d1327b0d19f")]
            public virtual Ranorex.Cell Cell99
            {
                get
                {
                    return _cell99Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Cell99 item info.
            /// </summary>
            [RepositoryItemInfo("060b7b7d-8350-4691-bfdf-5d1327b0d19f")]
            public virtual RepoItemInfo Cell99Info
            {
                get
                {
                    return _cell99Info;
                }
            }

            /// <summary>
            /// The Cell99000 item.
            /// </summary>
            [RepositoryItem("311f5664-708f-464d-b83d-4f5d05a9b1cc")]
            public virtual Ranorex.Cell Cell99000
            {
                get
                {
                    return _cell99000Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Cell99000 item info.
            /// </summary>
            [RepositoryItemInfo("311f5664-708f-464d-b83d-4f5d05a9b1cc")]
            public virtual RepoItemInfo Cell99000Info
            {
                get
                {
                    return _cell99000Info;
                }
            }
        }

        /// <summary>
        /// The GEOTOOLS1AppFolder folder.
        /// </summary>
        [RepositoryFolder("dea7cdfa-e2dc-4b32-8251-b3c5101d03a6")]
        public partial class GEOTOOLS1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ednameInfo;
            RepoItemInfo _nedmaxcontentInfo;
            RepoItemInfo _nedmincontentInfo;
            RepoItemInfo _применитьInfo;

            /// <summary>
            /// Creates a new GEOTOOLS1  folder.
            /// </summary>
            public GEOTOOLS1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("GEOTOOLS1", "/form[@name='NewComponentForm']", parentFolder, 30000, null, true, "dea7cdfa-e2dc-4b32-8251-b3c5101d03a6", "")
            {
                _ednameInfo = new RepoItemInfo(this, "EdName", "text[@name='edName']", 30000, null, "dff70535-1c83-497b-8815-df9f694d0d4c");
                _nedmaxcontentInfo = new RepoItemInfo(this, "NedMaxContent", "text[@name='nedMaxContent']", 30000, null, "e80e7216-2e3a-4c3a-a77b-28f690efeec1");
                _nedmincontentInfo = new RepoItemInfo(this, "NedMinContent", "text[@name='nedMinContent']", 30000, null, "eb0aa2b0-3999-4818-9c98-8c4a76e7dff0");
                _применитьInfo = new RepoItemInfo(this, "Применить", "button[@name='btnApply']", 30000, null, "c0f9301f-606c-4eeb-8469-f4871110dd1e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dea7cdfa-e2dc-4b32-8251-b3c5101d03a6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dea7cdfa-e2dc-4b32-8251-b3c5101d03a6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EdName item.
            /// </summary>
            [RepositoryItem("dff70535-1c83-497b-8815-df9f694d0d4c")]
            public virtual Ranorex.Text EdName
            {
                get
                {
                    return _ednameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EdName item info.
            /// </summary>
            [RepositoryItemInfo("dff70535-1c83-497b-8815-df9f694d0d4c")]
            public virtual RepoItemInfo EdNameInfo
            {
                get
                {
                    return _ednameInfo;
                }
            }

            /// <summary>
            /// The NedMaxContent item.
            /// </summary>
            [RepositoryItem("e80e7216-2e3a-4c3a-a77b-28f690efeec1")]
            public virtual Ranorex.Text NedMaxContent
            {
                get
                {
                    return _nedmaxcontentInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NedMaxContent item info.
            /// </summary>
            [RepositoryItemInfo("e80e7216-2e3a-4c3a-a77b-28f690efeec1")]
            public virtual RepoItemInfo NedMaxContentInfo
            {
                get
                {
                    return _nedmaxcontentInfo;
                }
            }

            /// <summary>
            /// The NedMinContent item.
            /// </summary>
            [RepositoryItem("eb0aa2b0-3999-4818-9c98-8c4a76e7dff0")]
            public virtual Ranorex.Text NedMinContent
            {
                get
                {
                    return _nedmincontentInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NedMinContent item info.
            /// </summary>
            [RepositoryItemInfo("eb0aa2b0-3999-4818-9c98-8c4a76e7dff0")]
            public virtual RepoItemInfo NedMinContentInfo
            {
                get
                {
                    return _nedmincontentInfo;
                }
            }

            /// <summary>
            /// The Применить item.
            /// </summary>
            [RepositoryItem("c0f9301f-606c-4eeb-8469-f4871110dd1e")]
            public virtual Ranorex.Button Применить
            {
                get
                {
                    return _применитьInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Применить item info.
            /// </summary>
            [RepositoryItemInfo("c0f9301f-606c-4eeb-8469-f4871110dd1e")]
            public virtual RepoItemInfo ПрименитьInfo
            {
                get
                {
                    return _применитьInfo;
                }
            }
        }

        /// <summary>
        /// The ЦветAppFolder folder.
        /// </summary>
        [RepositoryFolder("73e8a368-e784-4b98-b546-d9ce3ddeff9e")]
        public partial class ЦветAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text720Info;
            RepoItemInfo _buttonокInfo;

            /// <summary>
            /// Creates a new Цвет  folder.
            /// </summary>
            public ЦветAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Цвет", "/form[@title='Цвет']", parentFolder, 30000, null, true, "73e8a368-e784-4b98-b546-d9ce3ddeff9e", "")
            {
                _text720Info = new RepoItemInfo(this, "Text720", "text[@controlid='720']", 30000, null, "bafb5fb0-1da5-4f14-a672-cd4f554aef2b");
                _buttonокInfo = new RepoItemInfo(this, "ButtonОК", "button[@text='ОК']", 30000, null, "15ea6b78-4e05-4de9-8d13-cecd672ab8be");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("73e8a368-e784-4b98-b546-d9ce3ddeff9e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("73e8a368-e784-4b98-b546-d9ce3ddeff9e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text720 item.
            /// </summary>
            [RepositoryItem("bafb5fb0-1da5-4f14-a672-cd4f554aef2b")]
            public virtual Ranorex.Text Text720
            {
                get
                {
                    return _text720Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text720 item info.
            /// </summary>
            [RepositoryItemInfo("bafb5fb0-1da5-4f14-a672-cd4f554aef2b")]
            public virtual RepoItemInfo Text720Info
            {
                get
                {
                    return _text720Info;
                }
            }

            /// <summary>
            /// The ButtonОК item.
            /// </summary>
            [RepositoryItem("15ea6b78-4e05-4de9-8d13-cecd672ab8be")]
            public virtual Ranorex.Button ButtonОК
            {
                get
                {
                    return _buttonокInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonОК item info.
            /// </summary>
            [RepositoryItemInfo("15ea6b78-4e05-4de9-8d13-cecd672ab8be")]
            public virtual RepoItemInfo ButtonОКInfo
            {
                get
                {
                    return _buttonокInfo;
                }
            }
        }

        /// <summary>
        /// The GeoToolsИмпортДанныхAppFolder folder.
        /// </summary>
        [RepositoryFolder("f693525c-c24f-458f-8364-181cea85952a")]
        public partial class GeoToolsИмпортДанныхAppFolder : RepoGenBaseFolder
        {
            тпаитRepositoryFolders.PoleNameGr1Folder _polenamegr1;
            RepoItemInfo _openfilebtnInfo;
            RepoItemInfo _somebuttonInfo;
            RepoItemInfo _polenamegrInfo;
            RepoItemInfo _listnamegrInfo;
            RepoItemInfo _downInfo;
            RepoItemInfo _buttonupInfo;
            RepoItemInfo _copynamebtnInfo;
            RepoItemInfo _импортInfo;
            RepoItemInfo _bevel2Info;
            RepoItemInfo _закрытьInfo;
            RepoItemInfo _allpolecopbtnInfo;

            /// <summary>
            /// Creates a new GeoToolsИмпортДанных  folder.
            /// </summary>
            public GeoToolsИмпортДанныхAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GeoToolsИмпортДанных", "/form[@name='ExportDataForm']", parentFolder, 30000, null, true, "f693525c-c24f-458f-8364-181cea85952a", "")
            {
                _polenamegr1 = new тпаитRepositoryFolders.PoleNameGr1Folder(this);
                _openfilebtnInfo = new RepoItemInfo(this, "OpenFileBtn", "button[@name='OpenFileBtn']", 30000, null, "5a54c403-87ba-48a8-8a77-8ba9a26759f2");
                _somebuttonInfo = new RepoItemInfo(this, "SomeButton", "container[@name='GroupBox1']/?/?/button[@text='>']", 30000, null, "d9854e18-e17a-4890-aa42-85a26442ff91");
                _polenamegrInfo = new RepoItemInfo(this, "PoleNameGr", "table[@name='PoleNameGr']", 30000, null, "c8f0340d-03f4-4025-ab0c-c08ad10c1978");
                _listnamegrInfo = new RepoItemInfo(this, "ListNameGr", "table[@name='ListNameGr']", 30000, null, "13796f10-4403-49dc-a1c1-0920d051642f");
                _downInfo = new RepoItemInfo(this, "Down", "table[@name='ListNameGr']/?/?/button[@text='Down']", 30000, null, "e37a9593-2a7b-422f-b1b7-0c3b38020153");
                _buttonupInfo = new RepoItemInfo(this, "ButtonUp", "table[@name='ListNameGr']/?/?/button[@text='Up']", 30000, null, "a114eef5-0f89-404b-b1a5-da58489f751c");
                _copynamebtnInfo = new RepoItemInfo(this, "CopyNameBtn", "button[@name='CopyNameBtn']", 30000, null, "b35679e4-6dc7-4a9b-a166-13641191eda1");
                _импортInfo = new RepoItemInfo(this, "Импорт", "button[@name='ImportBtn']", 30000, null, "aff2035d-201c-48db-b265-c8df4313258e");
                _bevel2Info = new RepoItemInfo(this, "Bevel2", "container[@name='Bevel2']", 30000, null, "7066fd1b-bb09-4f44-99e0-c4b9135885fa");
                _закрытьInfo = new RepoItemInfo(this, "Закрыть", "button[@name='BitBtnExit']", 30000, null, "705f9cfe-e267-46c1-9426-5d0a4aa8849f");
                _allpolecopbtnInfo = new RepoItemInfo(this, "AllPoleCopBtn", "button[@name='AllPoleCopBtn']", 30000, null, "9b28ea1c-eb4e-49a2-8a36-310f99d631b9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f693525c-c24f-458f-8364-181cea85952a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f693525c-c24f-458f-8364-181cea85952a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OpenFileBtn item.
            /// </summary>
            [RepositoryItem("5a54c403-87ba-48a8-8a77-8ba9a26759f2")]
            public virtual Ranorex.Button OpenFileBtn
            {
                get
                {
                    return _openfilebtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OpenFileBtn item info.
            /// </summary>
            [RepositoryItemInfo("5a54c403-87ba-48a8-8a77-8ba9a26759f2")]
            public virtual RepoItemInfo OpenFileBtnInfo
            {
                get
                {
                    return _openfilebtnInfo;
                }
            }

            /// <summary>
            /// The SomeButton item.
            /// </summary>
            [RepositoryItem("d9854e18-e17a-4890-aa42-85a26442ff91")]
            public virtual Ranorex.Button SomeButton
            {
                get
                {
                    return _somebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SomeButton item info.
            /// </summary>
            [RepositoryItemInfo("d9854e18-e17a-4890-aa42-85a26442ff91")]
            public virtual RepoItemInfo SomeButtonInfo
            {
                get
                {
                    return _somebuttonInfo;
                }
            }

            /// <summary>
            /// The PoleNameGr item.
            /// </summary>
            [RepositoryItem("c8f0340d-03f4-4025-ab0c-c08ad10c1978")]
            public virtual Ranorex.Table PoleNameGr
            {
                get
                {
                    return _polenamegrInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The PoleNameGr item info.
            /// </summary>
            [RepositoryItemInfo("c8f0340d-03f4-4025-ab0c-c08ad10c1978")]
            public virtual RepoItemInfo PoleNameGrInfo
            {
                get
                {
                    return _polenamegrInfo;
                }
            }

            /// <summary>
            /// The ListNameGr item.
            /// </summary>
            [RepositoryItem("13796f10-4403-49dc-a1c1-0920d051642f")]
            public virtual Ranorex.Table ListNameGr
            {
                get
                {
                    return _listnamegrInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The ListNameGr item info.
            /// </summary>
            [RepositoryItemInfo("13796f10-4403-49dc-a1c1-0920d051642f")]
            public virtual RepoItemInfo ListNameGrInfo
            {
                get
                {
                    return _listnamegrInfo;
                }
            }

            /// <summary>
            /// The Down item.
            /// </summary>
            [RepositoryItem("e37a9593-2a7b-422f-b1b7-0c3b38020153")]
            public virtual Ranorex.Button Down
            {
                get
                {
                    return _downInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Down item info.
            /// </summary>
            [RepositoryItemInfo("e37a9593-2a7b-422f-b1b7-0c3b38020153")]
            public virtual RepoItemInfo DownInfo
            {
                get
                {
                    return _downInfo;
                }
            }

            /// <summary>
            /// The ButtonUp item.
            /// </summary>
            [RepositoryItem("a114eef5-0f89-404b-b1a5-da58489f751c")]
            public virtual Ranorex.Button ButtonUp
            {
                get
                {
                    return _buttonupInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonUp item info.
            /// </summary>
            [RepositoryItemInfo("a114eef5-0f89-404b-b1a5-da58489f751c")]
            public virtual RepoItemInfo ButtonUpInfo
            {
                get
                {
                    return _buttonupInfo;
                }
            }

            /// <summary>
            /// The CopyNameBtn item.
            /// </summary>
            [RepositoryItem("b35679e4-6dc7-4a9b-a166-13641191eda1")]
            public virtual Ranorex.Button CopyNameBtn
            {
                get
                {
                    return _copynamebtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CopyNameBtn item info.
            /// </summary>
            [RepositoryItemInfo("b35679e4-6dc7-4a9b-a166-13641191eda1")]
            public virtual RepoItemInfo CopyNameBtnInfo
            {
                get
                {
                    return _copynamebtnInfo;
                }
            }

            /// <summary>
            /// The Импорт item.
            /// </summary>
            [RepositoryItem("aff2035d-201c-48db-b265-c8df4313258e")]
            public virtual Ranorex.Button Импорт
            {
                get
                {
                    return _импортInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Импорт item info.
            /// </summary>
            [RepositoryItemInfo("aff2035d-201c-48db-b265-c8df4313258e")]
            public virtual RepoItemInfo ИмпортInfo
            {
                get
                {
                    return _импортInfo;
                }
            }

            /// <summary>
            /// The Bevel2 item.
            /// </summary>
            [RepositoryItem("7066fd1b-bb09-4f44-99e0-c4b9135885fa")]
            public virtual Ranorex.Container Bevel2
            {
                get
                {
                    return _bevel2Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Bevel2 item info.
            /// </summary>
            [RepositoryItemInfo("7066fd1b-bb09-4f44-99e0-c4b9135885fa")]
            public virtual RepoItemInfo Bevel2Info
            {
                get
                {
                    return _bevel2Info;
                }
            }

            /// <summary>
            /// The Закрыть item.
            /// </summary>
            [RepositoryItem("705f9cfe-e267-46c1-9426-5d0a4aa8849f")]
            public virtual Ranorex.Button Закрыть
            {
                get
                {
                    return _закрытьInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Закрыть item info.
            /// </summary>
            [RepositoryItemInfo("705f9cfe-e267-46c1-9426-5d0a4aa8849f")]
            public virtual RepoItemInfo ЗакрытьInfo
            {
                get
                {
                    return _закрытьInfo;
                }
            }

            /// <summary>
            /// The AllPoleCopBtn item.
            /// </summary>
            [RepositoryItem("9b28ea1c-eb4e-49a2-8a36-310f99d631b9")]
            public virtual Ranorex.Button AllPoleCopBtn
            {
                get
                {
                    return _allpolecopbtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AllPoleCopBtn item info.
            /// </summary>
            [RepositoryItemInfo("9b28ea1c-eb4e-49a2-8a36-310f99d631b9")]
            public virtual RepoItemInfo AllPoleCopBtnInfo
            {
                get
                {
                    return _allpolecopbtnInfo;
                }
            }

            /// <summary>
            /// The PoleNameGr1 folder.
            /// </summary>
            [RepositoryFolder("a73c1395-7aee-4709-8329-2753358df1a9")]
            public virtual тпаитRepositoryFolders.PoleNameGr1Folder PoleNameGr1
            {
                get { return _polenamegr1; }
            }
        }

        /// <summary>
        /// The PoleNameGr1Folder folder.
        /// </summary>
        [RepositoryFolder("a73c1395-7aee-4709-8329-2753358df1a9")]
        public partial class PoleNameGr1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _down1Info;
            RepoItemInfo _plineInfo;
            RepoItemInfo _cellxInfo;

            /// <summary>
            /// Creates a new PoleNameGr1  folder.
            /// </summary>
            public PoleNameGr1Folder(RepoGenBaseFolder parentFolder) :
                    base("PoleNameGr1", "table[@name='PoleNameGr']", parentFolder, 30000, null, false, "a73c1395-7aee-4709-8329-2753358df1a9", "")
            {
                _down1Info = new RepoItemInfo(this, "Down1", "?/?/button[@text='Down']", 30000, null, "70ba2d71-3dc7-4d92-aec9-5bf10bcf6193");
                _plineInfo = new RepoItemInfo(this, "PLine", "?/?/cell[@name='P_Line']", 30000, null, "9778a89f-4802-4644-9a6c-ddbb83c0537c");
                _cellxInfo = new RepoItemInfo(this, "CellX", "?/?/cell[@name='X']", 30000, null, "215639ed-330e-496b-b227-304ea1b04adb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a73c1395-7aee-4709-8329-2753358df1a9")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a73c1395-7aee-4709-8329-2753358df1a9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Down1 item.
            /// </summary>
            [RepositoryItem("70ba2d71-3dc7-4d92-aec9-5bf10bcf6193")]
            public virtual Ranorex.Button Down1
            {
                get
                {
                    return _down1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Down1 item info.
            /// </summary>
            [RepositoryItemInfo("70ba2d71-3dc7-4d92-aec9-5bf10bcf6193")]
            public virtual RepoItemInfo Down1Info
            {
                get
                {
                    return _down1Info;
                }
            }

            /// <summary>
            /// The PLine item.
            /// </summary>
            [RepositoryItem("9778a89f-4802-4644-9a6c-ddbb83c0537c")]
            public virtual Ranorex.Cell PLine
            {
                get
                {
                    return _plineInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The PLine item info.
            /// </summary>
            [RepositoryItemInfo("9778a89f-4802-4644-9a6c-ddbb83c0537c")]
            public virtual RepoItemInfo PLineInfo
            {
                get
                {
                    return _plineInfo;
                }
            }

            /// <summary>
            /// The CellX item.
            /// </summary>
            [RepositoryItem("215639ed-330e-496b-b227-304ea1b04adb")]
            public virtual Ranorex.Cell CellX
            {
                get
                {
                    return _cellxInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellX item info.
            /// </summary>
            [RepositoryItemInfo("215639ed-330e-496b-b227-304ea1b04adb")]
            public virtual RepoItemInfo CellXInfo
            {
                get
                {
                    return _cellxInfo;
                }
            }
        }

        /// <summary>
        /// The ОткрытиеAppFolder folder.
        /// </summary>
        [RepositoryFolder("a0549ae5-1e19-458b-90e5-1b322d0a130f")]
        public partial class ОткрытиеAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _someindicatorInfo;
            RepoItemInfo _tree100Info;
            RepoItemInfo _открытиеInfo;
            RepoItemInfo _combobox1136Info;
            RepoItemInfo _systemitemnamedisplayInfo;
            RepoItemInfo _buttonоткрытьInfo;
            RepoItemInfo _systemitemnamedisplay1Info;

            /// <summary>
            /// Creates a new Открытие  folder.
            /// </summary>
            public ОткрытиеAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Открытие", "/form[@title='Открытие']", parentFolder, 30000, null, true, "a0549ae5-1e19-458b-90e5-1b322d0a130f", "")
            {
                _someindicatorInfo = new RepoItemInfo(this, "SomeIndicator", "element[@class='DUIViewWndClassName']//tree[@controlid='100']/scrollbar[@style='Vertical']/indicator", 30000, null, "4605dbf2-77a6-48ea-bb81-ef704d64f637");
                _tree100Info = new RepoItemInfo(this, "Tree100", "element[@class='DUIViewWndClassName']/container/element[1]/?/?/tree[@controlid='100']", 30000, null, "aae25f63-951a-4067-8842-9bea83c1a28d");
                _открытиеInfo = new RepoItemInfo(this, "Открытие", "titlebar[@accessiblerole='TitleBar']", 30000, null, "1687be45-0cea-425f-ac3e-e5ef2702858e");
                _combobox1136Info = new RepoItemInfo(this, "ComboBox1136", "combobox[@controlid='1136']", 30000, null, "db7376e9-9ff8-4c29-b83b-83c70c77a9d1");
                _systemitemnamedisplayInfo = new RepoItemInfo(this, "SystemItemNameDisplay", "element[@class='DUIViewWndClassName']//container[@caption='ShellView']/?/?/listitem[@automationid='0']/text[@automationid='System.ItemNameDisplay']", 30000, null, "bbc922c0-b8ca-46d0-aab5-af184eb568d8");
                _buttonоткрытьInfo = new RepoItemInfo(this, "ButtonОткрыть", "button[@text='&Открыть']", 30000, null, "98eafcdf-e3c8-44d5-86aa-ab01c3aeb0d1");
                _systemitemnamedisplay1Info = new RepoItemInfo(this, "SystemItemNameDisplay1", "element[@class='DUIViewWndClassName']//container[@caption='ShellView']/?/?/listitem[@automationid='1']/text[@automationid='System.ItemNameDisplay']", 30000, null, "56af8da7-ef71-4386-a609-89b09ae32021");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a0549ae5-1e19-458b-90e5-1b322d0a130f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a0549ae5-1e19-458b-90e5-1b322d0a130f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeIndicator item.
            /// </summary>
            [RepositoryItem("4605dbf2-77a6-48ea-bb81-ef704d64f637")]
            public virtual Ranorex.Indicator SomeIndicator
            {
                get
                {
                    return _someindicatorInfo.CreateAdapter<Ranorex.Indicator>(true);
                }
            }

            /// <summary>
            /// The SomeIndicator item info.
            /// </summary>
            [RepositoryItemInfo("4605dbf2-77a6-48ea-bb81-ef704d64f637")]
            public virtual RepoItemInfo SomeIndicatorInfo
            {
                get
                {
                    return _someindicatorInfo;
                }
            }

            /// <summary>
            /// The Tree100 item.
            /// </summary>
            [RepositoryItem("aae25f63-951a-4067-8842-9bea83c1a28d")]
            public virtual Ranorex.Tree Tree100
            {
                get
                {
                    return _tree100Info.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The Tree100 item info.
            /// </summary>
            [RepositoryItemInfo("aae25f63-951a-4067-8842-9bea83c1a28d")]
            public virtual RepoItemInfo Tree100Info
            {
                get
                {
                    return _tree100Info;
                }
            }

            /// <summary>
            /// The Открытие item.
            /// </summary>
            [RepositoryItem("1687be45-0cea-425f-ac3e-e5ef2702858e")]
            public virtual Ranorex.TitleBar Открытие
            {
                get
                {
                    return _открытиеInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The Открытие item info.
            /// </summary>
            [RepositoryItemInfo("1687be45-0cea-425f-ac3e-e5ef2702858e")]
            public virtual RepoItemInfo ОткрытиеInfo
            {
                get
                {
                    return _открытиеInfo;
                }
            }

            /// <summary>
            /// The ComboBox1136 item.
            /// </summary>
            [RepositoryItem("db7376e9-9ff8-4c29-b83b-83c70c77a9d1")]
            public virtual Ranorex.ComboBox ComboBox1136
            {
                get
                {
                    return _combobox1136Info.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBox1136 item info.
            /// </summary>
            [RepositoryItemInfo("db7376e9-9ff8-4c29-b83b-83c70c77a9d1")]
            public virtual RepoItemInfo ComboBox1136Info
            {
                get
                {
                    return _combobox1136Info;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item.
            /// </summary>
            [RepositoryItem("bbc922c0-b8ca-46d0-aab5-af184eb568d8")]
            public virtual Ranorex.Text SystemItemNameDisplay
            {
                get
                {
                    return _systemitemnamedisplayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item info.
            /// </summary>
            [RepositoryItemInfo("bbc922c0-b8ca-46d0-aab5-af184eb568d8")]
            public virtual RepoItemInfo SystemItemNameDisplayInfo
            {
                get
                {
                    return _systemitemnamedisplayInfo;
                }
            }

            /// <summary>
            /// The ButtonОткрыть item.
            /// </summary>
            [RepositoryItem("98eafcdf-e3c8-44d5-86aa-ab01c3aeb0d1")]
            public virtual Ranorex.Button ButtonОткрыть
            {
                get
                {
                    return _buttonоткрытьInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonОткрыть item info.
            /// </summary>
            [RepositoryItemInfo("98eafcdf-e3c8-44d5-86aa-ab01c3aeb0d1")]
            public virtual RepoItemInfo ButtonОткрытьInfo
            {
                get
                {
                    return _buttonоткрытьInfo;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay1 item.
            /// </summary>
            [RepositoryItem("56af8da7-ef71-4386-a609-89b09ae32021")]
            public virtual Ranorex.Text SystemItemNameDisplay1
            {
                get
                {
                    return _systemitemnamedisplay1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay1 item info.
            /// </summary>
            [RepositoryItemInfo("56af8da7-ef71-4386-a609-89b09ae32021")]
            public virtual RepoItemInfo SystemItemNameDisplay1Info
            {
                get
                {
                    return _systemitemnamedisplay1Info;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("d5e97338-7963-4ea0-a3fb-03facc94dbb5")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _файлыmsexcelasteriskxlsasteriskxInfo;
            RepoItemInfo _сквустьяInfo;
            RepoItemInfo _скважиныInfo;
            RepoItemInfo _пробыскважиныInfo;
            RepoItemInfo _сквопробInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "d5e97338-7963-4ea0-a3fb-03facc94dbb5", "")
            {
                _файлыmsexcelasteriskxlsasteriskxInfo = new RepoItemInfo(this, "ФайлыMSExcelAsteriskXlsAsteriskX", "listitem[@text~'^Файлы\\ MS\\ Excel\\ \\(\\*\\.xls,\\ \\*\\.']", 30000, null, "51beb9bf-1b3b-4ae9-84e3-63d38332af99");
                _сквустьяInfo = new RepoItemInfo(this, "СквУстья", "listitem[@text='скв_устья']", 30000, null, "6b373381-aee7-429d-8126-5e84e9c0f83c");
                _скважиныInfo = new RepoItemInfo(this, "Скважины", "listitem[@text='Скважины']", 30000, null, "646dc31a-c360-4f8f-856e-acb184d0a91a");
                _пробыскважиныInfo = new RepoItemInfo(this, "ПробыСкважины", "listitem[@text='Пробы (скважины)']", 30000, null, "410de048-cba7-4026-bd4f-fbe74f5cbfce");
                _сквопробInfo = new RepoItemInfo(this, "СквОпроб", "listitem[@text='скв_опроб']", 30000, null, "c208adf0-c3b2-4571-a799-bc1490bc1f3c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d5e97338-7963-4ea0-a3fb-03facc94dbb5")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d5e97338-7963-4ea0-a3fb-03facc94dbb5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ФайлыMSExcelAsteriskXlsAsteriskX item.
            /// </summary>
            [RepositoryItem("51beb9bf-1b3b-4ae9-84e3-63d38332af99")]
            public virtual Ranorex.ListItem ФайлыMSExcelAsteriskXlsAsteriskX
            {
                get
                {
                    return _файлыmsexcelasteriskxlsasteriskxInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ФайлыMSExcelAsteriskXlsAsteriskX item info.
            /// </summary>
            [RepositoryItemInfo("51beb9bf-1b3b-4ae9-84e3-63d38332af99")]
            public virtual RepoItemInfo ФайлыMSExcelAsteriskXlsAsteriskXInfo
            {
                get
                {
                    return _файлыmsexcelasteriskxlsasteriskxInfo;
                }
            }

            /// <summary>
            /// The СквУстья item.
            /// </summary>
            [RepositoryItem("6b373381-aee7-429d-8126-5e84e9c0f83c")]
            public virtual Ranorex.ListItem СквУстья
            {
                get
                {
                    return _сквустьяInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The СквУстья item info.
            /// </summary>
            [RepositoryItemInfo("6b373381-aee7-429d-8126-5e84e9c0f83c")]
            public virtual RepoItemInfo СквУстьяInfo
            {
                get
                {
                    return _сквустьяInfo;
                }
            }

            /// <summary>
            /// The Скважины item.
            /// </summary>
            [RepositoryItem("646dc31a-c360-4f8f-856e-acb184d0a91a")]
            public virtual Ranorex.ListItem Скважины
            {
                get
                {
                    return _скважиныInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Скважины item info.
            /// </summary>
            [RepositoryItemInfo("646dc31a-c360-4f8f-856e-acb184d0a91a")]
            public virtual RepoItemInfo СкважиныInfo
            {
                get
                {
                    return _скважиныInfo;
                }
            }

            /// <summary>
            /// The ПробыСкважины item.
            /// </summary>
            [RepositoryItem("410de048-cba7-4026-bd4f-fbe74f5cbfce")]
            public virtual Ranorex.ListItem ПробыСкважины
            {
                get
                {
                    return _пробыскважиныInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ПробыСкважины item info.
            /// </summary>
            [RepositoryItemInfo("410de048-cba7-4026-bd4f-fbe74f5cbfce")]
            public virtual RepoItemInfo ПробыСкважиныInfo
            {
                get
                {
                    return _пробыскважиныInfo;
                }
            }

            /// <summary>
            /// The СквОпроб item.
            /// </summary>
            [RepositoryItem("c208adf0-c3b2-4571-a799-bc1490bc1f3c")]
            public virtual Ranorex.ListItem СквОпроб
            {
                get
                {
                    return _сквопробInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The СквОпроб item info.
            /// </summary>
            [RepositoryItemInfo("c208adf0-c3b2-4571-a799-bc1490bc1f3c")]
            public virtual RepoItemInfo СквОпробInfo
            {
                get
                {
                    return _сквопробInfo;
                }
            }
        }

        /// <summary>
        /// The МастерИмпортаШаг1Из1AppFolder folder.
        /// </summary>
        [RepositoryFolder("fda58a26-8107-4047-a116-8022caa7a130")]
        public partial class МастерИмпортаШаг1Из1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _somebuttonInfo;
            RepoItemInfo _razdnumInfo;
            RepoItemInfo _listnboxInfo;
            RepoItemInfo _titleindInfo;
            RepoItemInfo _готовоInfo;

            /// <summary>
            /// Creates a new МастерИмпортаШаг1Из1  folder.
            /// </summary>
            public МастерИмпортаШаг1Из1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("МастерИмпортаШаг1Из1", "/form[@name='MasterImportFrm']", parentFolder, 30000, null, true, "fda58a26-8107-4047-a116-8022caa7a130", "")
            {
                _somebuttonInfo = new RepoItemInfo(this, "SomeButton", "?/?/button[@text='>']", 30000, null, "acacfc7e-aa51-46e4-849d-c3424e5e86e4");
                _razdnumInfo = new RepoItemInfo(this, "RazdNum", "text[@name='RazdNum']", 30000, null, "35e591b6-d7f2-4fa5-9d4a-6e2676b17dd1");
                _listnboxInfo = new RepoItemInfo(this, "ListNBox", "combobox[@name='ListNBox']", 30000, null, "521180ef-1820-4591-9a64-cc45ca19a516");
                _titleindInfo = new RepoItemInfo(this, "TitleInd", "text[@name='TitleInd']", 30000, null, "27bd6a34-85b8-4305-a477-b3e1e962c06d");
                _готовоInfo = new RepoItemInfo(this, "Готово", "button[@name='GotovoBtn']", 30000, null, "15f99e05-f135-4503-9e9e-d42694eed625");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fda58a26-8107-4047-a116-8022caa7a130")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fda58a26-8107-4047-a116-8022caa7a130")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeButton item.
            /// </summary>
            [RepositoryItem("acacfc7e-aa51-46e4-849d-c3424e5e86e4")]
            public virtual Ranorex.Button SomeButton
            {
                get
                {
                    return _somebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SomeButton item info.
            /// </summary>
            [RepositoryItemInfo("acacfc7e-aa51-46e4-849d-c3424e5e86e4")]
            public virtual RepoItemInfo SomeButtonInfo
            {
                get
                {
                    return _somebuttonInfo;
                }
            }

            /// <summary>
            /// The RazdNum item.
            /// </summary>
            [RepositoryItem("35e591b6-d7f2-4fa5-9d4a-6e2676b17dd1")]
            public virtual Ranorex.Text RazdNum
            {
                get
                {
                    return _razdnumInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RazdNum item info.
            /// </summary>
            [RepositoryItemInfo("35e591b6-d7f2-4fa5-9d4a-6e2676b17dd1")]
            public virtual RepoItemInfo RazdNumInfo
            {
                get
                {
                    return _razdnumInfo;
                }
            }

            /// <summary>
            /// The ListNBox item.
            /// </summary>
            [RepositoryItem("521180ef-1820-4591-9a64-cc45ca19a516")]
            public virtual Ranorex.ComboBox ListNBox
            {
                get
                {
                    return _listnboxInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ListNBox item info.
            /// </summary>
            [RepositoryItemInfo("521180ef-1820-4591-9a64-cc45ca19a516")]
            public virtual RepoItemInfo ListNBoxInfo
            {
                get
                {
                    return _listnboxInfo;
                }
            }

            /// <summary>
            /// The TitleInd item.
            /// </summary>
            [RepositoryItem("27bd6a34-85b8-4305-a477-b3e1e962c06d")]
            public virtual Ranorex.Text TitleInd
            {
                get
                {
                    return _titleindInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TitleInd item info.
            /// </summary>
            [RepositoryItemInfo("27bd6a34-85b8-4305-a477-b3e1e962c06d")]
            public virtual RepoItemInfo TitleIndInfo
            {
                get
                {
                    return _titleindInfo;
                }
            }

            /// <summary>
            /// The Готово item.
            /// </summary>
            [RepositoryItem("15f99e05-f135-4503-9e9e-d42694eed625")]
            public virtual Ranorex.Button Готово
            {
                get
                {
                    return _готовоInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Готово item info.
            /// </summary>
            [RepositoryItemInfo("15f99e05-f135-4503-9e9e-d42694eed625")]
            public virtual RepoItemInfo ГотовоInfo
            {
                get
                {
                    return _готовоInfo;
                }
            }
        }

        /// <summary>
        /// The ПодтверждениеAppFolder folder.
        /// </summary>
        [RepositoryFolder("5f8e2632-4b1b-413d-8d82-41cf21c3f26a")]
        public partial class ПодтверждениеAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonдаInfo;

            /// <summary>
            /// Creates a new Подтверждение  folder.
            /// </summary>
            public ПодтверждениеAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Подтверждение", "/form[@title='Подтверждение']", parentFolder, 30000, null, true, "5f8e2632-4b1b-413d-8d82-41cf21c3f26a", "")
            {
                _buttonдаInfo = new RepoItemInfo(this, "ButtonДа", "?/?/element[@instance='0']/button[@text='&Да']", 30000, null, "247d117a-d1df-437f-bb14-ddf3c94f0241");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5f8e2632-4b1b-413d-8d82-41cf21c3f26a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5f8e2632-4b1b-413d-8d82-41cf21c3f26a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonДа item.
            /// </summary>
            [RepositoryItem("247d117a-d1df-437f-bb14-ddf3c94f0241")]
            public virtual Ranorex.Button ButtonДа
            {
                get
                {
                    return _buttonдаInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonДа item info.
            /// </summary>
            [RepositoryItemInfo("247d117a-d1df-437f-bb14-ddf3c94f0241")]
            public virtual RepoItemInfo ButtonДаInfo
            {
                get
                {
                    return _buttonдаInfo;
                }
            }
        }

        /// <summary>
        /// The ИнформацияAppFolder folder.
        /// </summary>
        [RepositoryFolder("d6f1efc0-7a57-4541-8c79-d67c47c7b91f")]
        public partial class ИнформацияAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonокInfo;

            /// <summary>
            /// Creates a new Информация  folder.
            /// </summary>
            public ИнформацияAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Информация", "/form[@title='Информация']", parentFolder, 30000, null, true, "d6f1efc0-7a57-4541-8c79-d67c47c7b91f", "")
            {
                _buttonокInfo = new RepoItemInfo(this, "ButtonОК", "?/?/element[@instance='0']/button[@text='О&К']", 30000, null, "e1681708-dfa8-42e7-ae93-e3c553f728a4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d6f1efc0-7a57-4541-8c79-d67c47c7b91f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d6f1efc0-7a57-4541-8c79-d67c47c7b91f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonОК item.
            /// </summary>
            [RepositoryItem("e1681708-dfa8-42e7-ae93-e3c553f728a4")]
            public virtual Ranorex.Button ButtonОК
            {
                get
                {
                    return _buttonокInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonОК item info.
            /// </summary>
            [RepositoryItemInfo("e1681708-dfa8-42e7-ae93-e3c553f728a4")]
            public virtual RepoItemInfo ButtonОКInfo
            {
                get
                {
                    return _buttonокInfo;
                }
            }
        }

        /// <summary>
        /// The ОшибкаAppFolder folder.
        /// </summary>
        [RepositoryFolder("dc261375-95a6-4162-a3ee-bb6b0f4b720e")]
        public partial class ОшибкаAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonокInfo;

            /// <summary>
            /// Creates a new Ошибка  folder.
            /// </summary>
            public ОшибкаAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Ошибка", "/form[@title='Ошибка']", parentFolder, 30000, null, true, "dc261375-95a6-4162-a3ee-bb6b0f4b720e", "")
            {
                _buttonокInfo = new RepoItemInfo(this, "ButtonОК", "?/?/element[@instance='0']/button[@text='О&К']", 30000, null, "f96cac4d-f849-474a-a960-d4490b45ddc4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dc261375-95a6-4162-a3ee-bb6b0f4b720e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dc261375-95a6-4162-a3ee-bb6b0f4b720e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonОК item.
            /// </summary>
            [RepositoryItem("f96cac4d-f849-474a-a960-d4490b45ddc4")]
            public virtual Ranorex.Button ButtonОК
            {
                get
                {
                    return _buttonокInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonОК item info.
            /// </summary>
            [RepositoryItemInfo("f96cac4d-f849-474a-a960-d4490b45ddc4")]
            public virtual RepoItemInfo ButtonОКInfo
            {
                get
                {
                    return _buttonокInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}