///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace eadcs
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the eadcsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("3423dfe6-0bb5-4987-89cb-7524c5fcd5e1")]
    public partial class eadcsRepository : RepoGenBaseFolder
    {
        static eadcsRepository instance = new eadcsRepository();
        eadcsRepositoryFolders.ИнформацияAppFolder _информация;
        eadcsRepositoryFolders.GeoTech3D7ГеологияМаркшейдеAppFolder _geotech3d7геологиямаркшейде;
        eadcsRepositoryFolders.GeoTechAppFolder _geotech;
        eadcsRepositoryFolders.GeoTech3DAppFolder _geotech3d;
        eadcsRepositoryFolders.GeoTech3D1AppFolder _geotech3d1;
        eadcsRepositoryFolders.GEOTECH3D2AppFolder _geotech3d2;
        eadcsRepositoryFolders.ОткрытиеAppFolder _открытие;
        eadcsRepositoryFolders.List1000AppFolder _list1000;
        eadcsRepositoryFolders.GEOTECH3D3AppFolder _geotech3d3;
        eadcsRepositoryFolders.GEOTECH3D4AppFolder _geotech3d4;
        eadcsRepositoryFolders.ExplorerAppFolder _explorer;

        /// <summary>
        /// Gets the singleton class instance representing the eadcsRepository element repository.
        /// </summary>
        [RepositoryFolder("3423dfe6-0bb5-4987-89cb-7524c5fcd5e1")]
        public static eadcsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public eadcsRepository() 
            : base("eadcsRepository", "/", null, 0, false, "3423dfe6-0bb5-4987-89cb-7524c5fcd5e1", ".\\RepositoryImages\\eadcsRepository3423dfe6.rximgres")
        {
            _информация = new eadcsRepositoryFolders.ИнформацияAppFolder(this);
            _geotech3d7геологиямаркшейде = new eadcsRepositoryFolders.GeoTech3D7ГеологияМаркшейдеAppFolder(this);
            _geotech = new eadcsRepositoryFolders.GeoTechAppFolder(this);
            _geotech3d = new eadcsRepositoryFolders.GeoTech3DAppFolder(this);
            _geotech3d1 = new eadcsRepositoryFolders.GeoTech3D1AppFolder(this);
            _geotech3d2 = new eadcsRepositoryFolders.GEOTECH3D2AppFolder(this);
            _открытие = new eadcsRepositoryFolders.ОткрытиеAppFolder(this);
            _list1000 = new eadcsRepositoryFolders.List1000AppFolder(this);
            _geotech3d3 = new eadcsRepositoryFolders.GEOTECH3D3AppFolder(this);
            _geotech3d4 = new eadcsRepositoryFolders.GEOTECH3D4AppFolder(this);
            _explorer = new eadcsRepositoryFolders.ExplorerAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3423dfe6-0bb5-4987-89cb-7524c5fcd5e1")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Информация folder.
        /// </summary>
        [RepositoryFolder("f11760d7-a518-47e3-b0f5-71bc9fa5ab16")]
        public virtual eadcsRepositoryFolders.ИнформацияAppFolder Информация
        {
            get { return _информация; }
        }

        /// <summary>
        /// The GeoTech3D7ГеологияМаркшейде folder.
        /// </summary>
        [RepositoryFolder("22480a9a-c956-490e-b54d-c933c173c7db")]
        public virtual eadcsRepositoryFolders.GeoTech3D7ГеологияМаркшейдеAppFolder GeoTech3D7ГеологияМаркшейде
        {
            get { return _geotech3d7геологиямаркшейде; }
        }

        /// <summary>
        /// The GeoTech folder.
        /// </summary>
        [RepositoryFolder("6a946209-e1da-4f3f-9e5b-a7ee8d02f51d")]
        public virtual eadcsRepositoryFolders.GeoTechAppFolder GeoTech
        {
            get { return _geotech; }
        }

        /// <summary>
        /// The GeoTech3D folder.
        /// </summary>
        [RepositoryFolder("f209221a-212f-4ca2-838c-d1672aeea4b9")]
        public virtual eadcsRepositoryFolders.GeoTech3DAppFolder GeoTech3D
        {
            get { return _geotech3d; }
        }

        /// <summary>
        /// The GeoTech3D1 folder.
        /// </summary>
        [RepositoryFolder("df21fda6-7ded-4de1-92cd-c868df5919a8")]
        public virtual eadcsRepositoryFolders.GeoTech3D1AppFolder GeoTech3D1
        {
            get { return _geotech3d1; }
        }

        /// <summary>
        /// The GEOTECH3D2 folder.
        /// </summary>
        [RepositoryFolder("526d5b66-ae62-48a1-a77a-3d6eb8b11a0f")]
        public virtual eadcsRepositoryFolders.GEOTECH3D2AppFolder GEOTECH3D2
        {
            get { return _geotech3d2; }
        }

        /// <summary>
        /// The Открытие folder.
        /// </summary>
        [RepositoryFolder("b98b1967-7971-4da3-b1de-e3344c618477")]
        public virtual eadcsRepositoryFolders.ОткрытиеAppFolder Открытие
        {
            get { return _открытие; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("2f740ed7-ad26-4e0c-954c-49953e0f76c3")]
        public virtual eadcsRepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }

        /// <summary>
        /// The GEOTECH3D3 folder.
        /// </summary>
        [RepositoryFolder("2a82268b-85f0-45af-8248-1e95388ac608")]
        public virtual eadcsRepositoryFolders.GEOTECH3D3AppFolder GEOTECH3D3
        {
            get { return _geotech3d3; }
        }

        /// <summary>
        /// The GEOTECH3D4 folder.
        /// </summary>
        [RepositoryFolder("2df0d4a1-d329-45e1-8c0d-e0359fed0d6e")]
        public virtual eadcsRepositoryFolders.GEOTECH3D4AppFolder GEOTECH3D4
        {
            get { return _geotech3d4; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("ae76c50c-1226-4991-aa6f-d9528b9ea9d9")]
        public virtual eadcsRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class eadcsRepositoryFolders
    {
        /// <summary>
        /// The ИнформацияAppFolder folder.
        /// </summary>
        [RepositoryFolder("f11760d7-a518-47e3-b0f5-71bc9fa5ab16")]
        public partial class ИнформацияAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonокInfo;
            RepoItemInfo _buttonдаInfo;

            /// <summary>
            /// Creates a new Информация  folder.
            /// </summary>
            public ИнформацияAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Информация", "/form[@title='Информация']", parentFolder, 30000, null, true, "f11760d7-a518-47e3-b0f5-71bc9fa5ab16", "")
            {
                _buttonокInfo = new RepoItemInfo(this, "ButtonОК", "?/?/element[@instance='0']/button[@text='О&К']", 30000, null, "91110a86-3977-4a4c-bbc2-3214ca1180f9");
                _buttonдаInfo = new RepoItemInfo(this, "ButtonДа", "?/?/element[@instance='0']/button[@text='&Да']", 30000, null, "e19a022d-2243-45c4-ba2b-af7130e33097");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f11760d7-a518-47e3-b0f5-71bc9fa5ab16")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f11760d7-a518-47e3-b0f5-71bc9fa5ab16")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonОК item.
            /// </summary>
            [RepositoryItem("91110a86-3977-4a4c-bbc2-3214ca1180f9")]
            public virtual Ranorex.Button ButtonОК
            {
                get
                {
                    return _buttonокInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonОК item info.
            /// </summary>
            [RepositoryItemInfo("91110a86-3977-4a4c-bbc2-3214ca1180f9")]
            public virtual RepoItemInfo ButtonОКInfo
            {
                get
                {
                    return _buttonокInfo;
                }
            }

            /// <summary>
            /// The ButtonДа item.
            /// </summary>
            [RepositoryItem("e19a022d-2243-45c4-ba2b-af7130e33097")]
            public virtual Ranorex.Button ButtonДа
            {
                get
                {
                    return _buttonдаInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonДа item info.
            /// </summary>
            [RepositoryItemInfo("e19a022d-2243-45c4-ba2b-af7130e33097")]
            public virtual RepoItemInfo ButtonДаInfo
            {
                get
                {
                    return _buttonдаInfo;
                }
            }
        }

        /// <summary>
        /// The GeoTech3D7ГеологияМаркшейдеAppFolder folder.
        /// </summary>
        [RepositoryFolder("22480a9a-c956-490e-b54d-c933c173c7db")]
        public partial class GeoTech3D7ГеологияМаркшейдеAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _символInfo;
            RepoItemInfo _рабочеепространствоInfo;
            RepoItemInfo _someelementInfo;
            RepoItemInfo _objinspInfo;
            RepoItemInfo _propokbtnInfo;
            RepoItemInfo _someelement1Info;
            RepoItemInfo _form65280Info;
            RepoItemInfo _действияInfo;

            /// <summary>
            /// Creates a new GeoTech3D7ГеологияМаркшейде  folder.
            /// </summary>
            public GeoTech3D7ГеологияМаркшейдеAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GeoTech3D7ГеологияМаркшейде", "/form[@name='MainForm' and @title~'^GeoTech-3D\\ 7\\ \\|\\ \\ \\ \\ \\ \\ \\ \\ Гео']", parentFolder, 30000, null, true, "22480a9a-c956-490e-b54d-c933c173c7db", "")
            {
                _символInfo = new RepoItemInfo(this, "Символ", "?/?/menuitem[@name='SymbolItm']", 30000, null, "622d1d8d-88b8-43cb-959d-6677df50c673");
                _рабочеепространствоInfo = new RepoItemInfo(this, "РабочееПространство", "container[@accessiblename='Рабочее пространство']", 30000, null, "a6f72f19-42da-4e93-b5e8-a2aba151aab1");
                _someelementInfo = new RepoItemInfo(this, "SomeElement", "element[@name='LeftControlBar']/form[@title='Объекты']/element[1]", 30000, null, "e84e7751-2510-494a-a855-3d629af13f14");
                _objinspInfo = new RepoItemInfo(this, "ObjInsp", "container[@name='LeftDockPanel']/form[@name='OKBottomDlg']/?/?/container[@name='PropertyTab']//tree[@name='ObjInsp']", 30000, null, "f69c3616-f3f1-45c6-88f3-a3417da8d044");
                _propokbtnInfo = new RepoItemInfo(this, "PropOkBtn", "container[@name='LeftDockPanel']/form[@name='OKBottomDlg']//element[@name='PropOkBtn']", 30000, null, "c03787a6-c29d-4673-a8c6-6a1f210d15fc");
                _someelement1Info = new RepoItemInfo(this, "SomeElement1", "element[@name='LeftControlBar']/form[@title='Редактирование']/element[5]", 30000, null, "865c4b80-3d52-4d1c-bc5c-23767d24d4df");
                _form65280Info = new RepoItemInfo(this, "Form65280", "form[@name='MDIChild']", 30000, null, "26da9ec3-babd-4771-b9dd-63baf4c0a8f7");
                _действияInfo = new RepoItemInfo(this, "Действия", "?/?/menuitem[@name='miMainActions']", 30000, null, "2f5fa7be-2e74-43e0-bca3-ae4b7df618e1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("22480a9a-c956-490e-b54d-c933c173c7db")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("22480a9a-c956-490e-b54d-c933c173c7db")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Символ item.
            /// </summary>
            [RepositoryItem("622d1d8d-88b8-43cb-959d-6677df50c673")]
            public virtual Ranorex.MenuItem Символ
            {
                get
                {
                    return _символInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Символ item info.
            /// </summary>
            [RepositoryItemInfo("622d1d8d-88b8-43cb-959d-6677df50c673")]
            public virtual RepoItemInfo СимволInfo
            {
                get
                {
                    return _символInfo;
                }
            }

            /// <summary>
            /// The РабочееПространство item.
            /// </summary>
            [RepositoryItem("a6f72f19-42da-4e93-b5e8-a2aba151aab1")]
            public virtual Ranorex.Container РабочееПространство
            {
                get
                {
                    return _рабочеепространствоInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The РабочееПространство item info.
            /// </summary>
            [RepositoryItemInfo("a6f72f19-42da-4e93-b5e8-a2aba151aab1")]
            public virtual RepoItemInfo РабочееПространствоInfo
            {
                get
                {
                    return _рабочеепространствоInfo;
                }
            }

            /// <summary>
            /// The SomeElement item.
            /// </summary>
            [RepositoryItem("e84e7751-2510-494a-a855-3d629af13f14")]
            public virtual Ranorex.Unknown SomeElement
            {
                get
                {
                    return _someelementInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SomeElement item info.
            /// </summary>
            [RepositoryItemInfo("e84e7751-2510-494a-a855-3d629af13f14")]
            public virtual RepoItemInfo SomeElementInfo
            {
                get
                {
                    return _someelementInfo;
                }
            }

            /// <summary>
            /// The ObjInsp item.
            /// </summary>
            [RepositoryItem("f69c3616-f3f1-45c6-88f3-a3417da8d044")]
            public virtual Ranorex.Tree ObjInsp
            {
                get
                {
                    return _objinspInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The ObjInsp item info.
            /// </summary>
            [RepositoryItemInfo("f69c3616-f3f1-45c6-88f3-a3417da8d044")]
            public virtual RepoItemInfo ObjInspInfo
            {
                get
                {
                    return _objinspInfo;
                }
            }

            /// <summary>
            /// The PropOkBtn item.
            /// </summary>
            [RepositoryItem("c03787a6-c29d-4673-a8c6-6a1f210d15fc")]
            public virtual Ranorex.Unknown PropOkBtn
            {
                get
                {
                    return _propokbtnInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The PropOkBtn item info.
            /// </summary>
            [RepositoryItemInfo("c03787a6-c29d-4673-a8c6-6a1f210d15fc")]
            public virtual RepoItemInfo PropOkBtnInfo
            {
                get
                {
                    return _propokbtnInfo;
                }
            }

            /// <summary>
            /// The SomeElement1 item.
            /// </summary>
            [RepositoryItem("865c4b80-3d52-4d1c-bc5c-23767d24d4df")]
            public virtual Ranorex.Unknown SomeElement1
            {
                get
                {
                    return _someelement1Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SomeElement1 item info.
            /// </summary>
            [RepositoryItemInfo("865c4b80-3d52-4d1c-bc5c-23767d24d4df")]
            public virtual RepoItemInfo SomeElement1Info
            {
                get
                {
                    return _someelement1Info;
                }
            }

            /// <summary>
            /// The Form65280 item.
            /// </summary>
            [RepositoryItem("26da9ec3-babd-4771-b9dd-63baf4c0a8f7")]
            public virtual Ranorex.Form Form65280
            {
                get
                {
                    return _form65280Info.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Form65280 item info.
            /// </summary>
            [RepositoryItemInfo("26da9ec3-babd-4771-b9dd-63baf4c0a8f7")]
            public virtual RepoItemInfo Form65280Info
            {
                get
                {
                    return _form65280Info;
                }
            }

            /// <summary>
            /// The Действия item.
            /// </summary>
            [RepositoryItem("2f5fa7be-2e74-43e0-bca3-ae4b7df618e1")]
            public virtual Ranorex.MenuItem Действия
            {
                get
                {
                    return _действияInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Действия item info.
            /// </summary>
            [RepositoryItemInfo("2f5fa7be-2e74-43e0-bca3-ae4b7df618e1")]
            public virtual RepoItemInfo ДействияInfo
            {
                get
                {
                    return _действияInfo;
                }
            }
        }

        /// <summary>
        /// The GeoTechAppFolder folder.
        /// </summary>
        [RepositoryFolder("6a946209-e1da-4f3f-9e5b-a7ee8d02f51d")]
        public partial class GeoTechAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _создатьctrlplusnInfo;
            RepoItemInfo _импортизфайлаInfo;

            /// <summary>
            /// Creates a new GeoTech  folder.
            /// </summary>
            public GeoTechAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GeoTech", "/contextmenu[@processname='GeoTech']", parentFolder, 30000, null, false, "6a946209-e1da-4f3f-9e5b-a7ee8d02f51d", "")
            {
                _создатьctrlplusnInfo = new RepoItemInfo(this, "СоздатьCtrlPlusN", "?/?/menuitem[@accessiblename='Создать...Ctrl+N']", 30000, null, "3646a436-2a72-48e7-b25a-e250b9f41a3d");
                _импортизфайлаInfo = new RepoItemInfo(this, "ИмпортИзФайла", "?/?/menuitem[@accessiblename='Импорт из файла']", 30000, null, "179a2b45-ab85-4225-931a-b4b07ec7ebbe");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6a946209-e1da-4f3f-9e5b-a7ee8d02f51d")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6a946209-e1da-4f3f-9e5b-a7ee8d02f51d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The СоздатьCtrlPlusN item.
            /// </summary>
            [RepositoryItem("3646a436-2a72-48e7-b25a-e250b9f41a3d")]
            public virtual Ranorex.MenuItem СоздатьCtrlPlusN
            {
                get
                {
                    return _создатьctrlplusnInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The СоздатьCtrlPlusN item info.
            /// </summary>
            [RepositoryItemInfo("3646a436-2a72-48e7-b25a-e250b9f41a3d")]
            public virtual RepoItemInfo СоздатьCtrlPlusNInfo
            {
                get
                {
                    return _создатьctrlplusnInfo;
                }
            }

            /// <summary>
            /// The ИмпортИзФайла item.
            /// </summary>
            [RepositoryItem("179a2b45-ab85-4225-931a-b4b07ec7ebbe")]
            public virtual Ranorex.MenuItem ИмпортИзФайла
            {
                get
                {
                    return _импортизфайлаInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ИмпортИзФайла item info.
            /// </summary>
            [RepositoryItemInfo("179a2b45-ab85-4225-931a-b4b07ec7ebbe")]
            public virtual RepoItemInfo ИмпортИзФайлаInfo
            {
                get
                {
                    return _импортизфайлаInfo;
                }
            }
        }

        /// <summary>
        /// The GeoTech3DAppFolder folder.
        /// </summary>
        [RepositoryFolder("f209221a-212f-4ca2-838c-d1672aeea4b9")]
        public partial class GeoTech3DAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _sbtcreateprojectInfo;

            /// <summary>
            /// Creates a new GeoTech3D  folder.
            /// </summary>
            public GeoTech3DAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GeoTech3D", "/form[@name='DualListDlg']", parentFolder, 30000, null, true, "f209221a-212f-4ca2-838c-d1672aeea4b9", "")
            {
                _sbtcreateprojectInfo = new RepoItemInfo(this, "SbtCreateProject", "button[@name='sbtCreateProject']", 30000, null, "f9d6b341-558f-4845-b07d-5a97ceab7d4c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f209221a-212f-4ca2-838c-d1672aeea4b9")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f209221a-212f-4ca2-838c-d1672aeea4b9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SbtCreateProject item.
            /// </summary>
            [RepositoryItem("f9d6b341-558f-4845-b07d-5a97ceab7d4c")]
            public virtual Ranorex.Button SbtCreateProject
            {
                get
                {
                    return _sbtcreateprojectInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SbtCreateProject item info.
            /// </summary>
            [RepositoryItemInfo("f9d6b341-558f-4845-b07d-5a97ceab7d4c")]
            public virtual RepoItemInfo SbtCreateProjectInfo
            {
                get
                {
                    return _sbtcreateprojectInfo;
                }
            }
        }

        /// <summary>
        /// The GeoTech3D1AppFolder folder.
        /// </summary>
        [RepositoryFolder("df21fda6-7ded-4de1-92cd-c868df5919a8")]
        public partial class GeoTech3D1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _edprojectnameInfo;
            RepoItemInfo _применитьInfo;

            /// <summary>
            /// Creates a new GeoTech3D1  folder.
            /// </summary>
            public GeoTech3D1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("GeoTech3D1", "/form[@name='NewNameProj']", parentFolder, 30000, null, true, "df21fda6-7ded-4de1-92cd-c868df5919a8", "")
            {
                _edprojectnameInfo = new RepoItemInfo(this, "EdProjectName", "text[@name='edProjectName']", 30000, null, "918632d5-2a79-4d39-9aae-2b283ce8413f");
                _применитьInfo = new RepoItemInfo(this, "Применить", "button[@name='btnApply']", 30000, null, "3e67fec9-7b26-4907-b37c-a383e103a68d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("df21fda6-7ded-4de1-92cd-c868df5919a8")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("df21fda6-7ded-4de1-92cd-c868df5919a8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EdProjectName item.
            /// </summary>
            [RepositoryItem("918632d5-2a79-4d39-9aae-2b283ce8413f")]
            public virtual Ranorex.Text EdProjectName
            {
                get
                {
                    return _edprojectnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EdProjectName item info.
            /// </summary>
            [RepositoryItemInfo("918632d5-2a79-4d39-9aae-2b283ce8413f")]
            public virtual RepoItemInfo EdProjectNameInfo
            {
                get
                {
                    return _edprojectnameInfo;
                }
            }

            /// <summary>
            /// The Применить item.
            /// </summary>
            [RepositoryItem("3e67fec9-7b26-4907-b37c-a383e103a68d")]
            public virtual Ranorex.Button Применить
            {
                get
                {
                    return _применитьInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Применить item info.
            /// </summary>
            [RepositoryItemInfo("3e67fec9-7b26-4907-b37c-a383e103a68d")]
            public virtual RepoItemInfo ПрименитьInfo
            {
                get
                {
                    return _применитьInfo;
                }
            }
        }

        /// <summary>
        /// The GEOTECH3D2AppFolder folder.
        /// </summary>
        [RepositoryFolder("526d5b66-ae62-48a1-a77a-3d6eb8b11a0f")]
        public partial class GEOTECH3D2AppFolder : RepoGenBaseFolder
        {
            eadcsRepositoryFolders.TabbedNotebook1Folder _tabbednotebook1;
            RepoItemInfo _выполнитьInfo;

            /// <summary>
            /// Creates a new GEOTECH3D2  folder.
            /// </summary>
            public GEOTECH3D2AppFolder(RepoGenBaseFolder parentFolder) :
                    base("GEOTECH3D2", "/form[@name='GeoOptions']", parentFolder, 30000, null, true, "526d5b66-ae62-48a1-a77a-3d6eb8b11a0f", "")
            {
                _tabbednotebook1 = new eadcsRepositoryFolders.TabbedNotebook1Folder(this);
                _выполнитьInfo = new RepoItemInfo(this, "Выполнить", "button[@name='OKBtn']", 30000, null, "4ecfdeb5-0797-47e6-833f-caa0fa264dc4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("526d5b66-ae62-48a1-a77a-3d6eb8b11a0f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("526d5b66-ae62-48a1-a77a-3d6eb8b11a0f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Выполнить item.
            /// </summary>
            [RepositoryItem("4ecfdeb5-0797-47e6-833f-caa0fa264dc4")]
            public virtual Ranorex.Button Выполнить
            {
                get
                {
                    return _выполнитьInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Выполнить item info.
            /// </summary>
            [RepositoryItemInfo("4ecfdeb5-0797-47e6-833f-caa0fa264dc4")]
            public virtual RepoItemInfo ВыполнитьInfo
            {
                get
                {
                    return _выполнитьInfo;
                }
            }

            /// <summary>
            /// The TabbedNotebook1 folder.
            /// </summary>
            [RepositoryFolder("e7715fec-e219-4184-9246-1dda29aa73f5")]
            public virtual eadcsRepositoryFolders.TabbedNotebook1Folder TabbedNotebook1
            {
                get { return _tabbednotebook1; }
            }
        }

        /// <summary>
        /// The TabbedNotebook1Folder folder.
        /// </summary>
        [RepositoryFolder("e7715fec-e219-4184-9246-1dda29aa73f5")]
        public partial class TabbedNotebook1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _xmaxeditInfo;
            RepoItemInfo _xmineditInfo;
            RepoItemInfo _ymaxeditInfo;
            RepoItemInfo _ymineditInfo;
            RepoItemInfo _containerpnlInfo;

            /// <summary>
            /// Creates a new TabbedNotebook1  folder.
            /// </summary>
            public TabbedNotebook1Folder(RepoGenBaseFolder parentFolder) :
                    base("TabbedNotebook1", "tabpagelist[@name='TabbedNotebook1']", parentFolder, 30000, null, false, "e7715fec-e219-4184-9246-1dda29aa73f5", "")
            {
                _xmaxeditInfo = new RepoItemInfo(this, "XmaxEdit", ".//text[@name='XmaxEdit']", 30000, null, "726da990-0934-444f-ba46-8ed9b8202551");
                _xmineditInfo = new RepoItemInfo(this, "XminEdit", ".//text[@name='XminEdit']", 30000, null, "b8cb5ace-ee38-46e1-9150-3a9d3d068cb0");
                _ymaxeditInfo = new RepoItemInfo(this, "YmaxEdit", ".//text[@name='YmaxEdit']", 30000, null, "bd11cb47-3260-4d78-9ea4-8deac35d058d");
                _ymineditInfo = new RepoItemInfo(this, "YminEdit", ".//text[@name='YminEdit']", 30000, null, "ed55ecfe-1314-4842-976a-abfcc6e56f0a");
                _containerpnlInfo = new RepoItemInfo(this, "ContainerPnl", "?/?/container[@name='Pnl']", 30000, null, "29ae2e3f-49f4-4839-8102-20ccf530a142");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e7715fec-e219-4184-9246-1dda29aa73f5")]
            public virtual Ranorex.TabPageList Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPageList>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e7715fec-e219-4184-9246-1dda29aa73f5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The XmaxEdit item.
            /// </summary>
            [RepositoryItem("726da990-0934-444f-ba46-8ed9b8202551")]
            public virtual Ranorex.Text XmaxEdit
            {
                get
                {
                    return _xmaxeditInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The XmaxEdit item info.
            /// </summary>
            [RepositoryItemInfo("726da990-0934-444f-ba46-8ed9b8202551")]
            public virtual RepoItemInfo XmaxEditInfo
            {
                get
                {
                    return _xmaxeditInfo;
                }
            }

            /// <summary>
            /// The XminEdit item.
            /// </summary>
            [RepositoryItem("b8cb5ace-ee38-46e1-9150-3a9d3d068cb0")]
            public virtual Ranorex.Text XminEdit
            {
                get
                {
                    return _xmineditInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The XminEdit item info.
            /// </summary>
            [RepositoryItemInfo("b8cb5ace-ee38-46e1-9150-3a9d3d068cb0")]
            public virtual RepoItemInfo XminEditInfo
            {
                get
                {
                    return _xmineditInfo;
                }
            }

            /// <summary>
            /// The YmaxEdit item.
            /// </summary>
            [RepositoryItem("bd11cb47-3260-4d78-9ea4-8deac35d058d")]
            public virtual Ranorex.Text YmaxEdit
            {
                get
                {
                    return _ymaxeditInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The YmaxEdit item info.
            /// </summary>
            [RepositoryItemInfo("bd11cb47-3260-4d78-9ea4-8deac35d058d")]
            public virtual RepoItemInfo YmaxEditInfo
            {
                get
                {
                    return _ymaxeditInfo;
                }
            }

            /// <summary>
            /// The YminEdit item.
            /// </summary>
            [RepositoryItem("ed55ecfe-1314-4842-976a-abfcc6e56f0a")]
            public virtual Ranorex.Text YminEdit
            {
                get
                {
                    return _ymineditInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The YminEdit item info.
            /// </summary>
            [RepositoryItemInfo("ed55ecfe-1314-4842-976a-abfcc6e56f0a")]
            public virtual RepoItemInfo YminEditInfo
            {
                get
                {
                    return _ymineditInfo;
                }
            }

            /// <summary>
            /// The ContainerPnl item.
            /// </summary>
            [RepositoryItem("29ae2e3f-49f4-4839-8102-20ccf530a142")]
            public virtual Ranorex.Container ContainerPnl
            {
                get
                {
                    return _containerpnlInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerPnl item info.
            /// </summary>
            [RepositoryItemInfo("29ae2e3f-49f4-4839-8102-20ccf530a142")]
            public virtual RepoItemInfo ContainerPnlInfo
            {
                get
                {
                    return _containerpnlInfo;
                }
            }
        }

        /// <summary>
        /// The ОткрытиеAppFolder folder.
        /// </summary>
        [RepositoryFolder("b98b1967-7971-4da3-b1de-e3344c618477")]
        public partial class ОткрытиеAppFolder : RepoGenBaseFolder
        {
            eadcsRepositoryFolders.ShellViewFolder _shellview;
            eadcsRepositoryFolders.Tree1001Folder _tree1001;
            RepoItemInfo _ctrlnotifysinkInfo;
            RepoItemInfo _somebuttonInfo;
            RepoItemInfo _базаобъектовгеологияInfo;
            RepoItemInfo _somebutton1Info;
            RepoItemInfo _buttonоткрытьInfo;
            RepoItemInfo _toolbar1001Info;
            RepoItemInfo _combobox1148Info;

            /// <summary>
            /// Creates a new Открытие  folder.
            /// </summary>
            public ОткрытиеAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Открытие", "/form[@title='Открытие']", parentFolder, 30000, null, true, "b98b1967-7971-4da3-b1de-e3344c618477", "")
            {
                _shellview = new eadcsRepositoryFolders.ShellViewFolder(this);
                _tree1001 = new eadcsRepositoryFolders.Tree1001Folder(this);
                _ctrlnotifysinkInfo = new RepoItemInfo(this, "CtrlNotifySink", "element[@class='DUIViewWndClassName']//container[@caption='ShellView']/container/container[2]", 30000, null, "4a85c9d2-6cf1-437a-9f8b-adf20acba2bf");
                _somebuttonInfo = new RepoItemInfo(this, "SomeButton", "combobox[@controlid='1136']/button[@text='>']", 30000, null, "abf98f0b-88dd-4be7-b838-3b6eece5ad68");
                _базаобъектовгеологияInfo = new RepoItemInfo(this, "БазаОбъектовГеология", "element[@class='DUIViewWndClassName']/container[@class='DirectUIHWND']/element[@instance='0']/?/?/tree[@controlid='100']//treeitem[@text='Локальный диск (D:)']//treeitem[@text='База объектов геология']", 30000, null, "a7b5c870-a355-430c-b8ab-d308d22e5116");
                _somebutton1Info = new RepoItemInfo(this, "SomeButton1", "?/?/button[@text='>']", 30000, null, "f14f78a9-db7c-42a1-9ebc-5e08b71589ca");
                _buttonоткрытьInfo = new RepoItemInfo(this, "ButtonОткрыть", "button[@text='&Открыть']", 30000, null, "5f827be2-bb58-4634-b936-efc7455f435f");
                _toolbar1001Info = new RepoItemInfo(this, "ToolBar1001", "element[@class='WorkerW']/?/?/element[@controlid='41477']//toolbar[@controlid='1001']", 30000, null, "58f9fe9a-d811-4845-a3d0-7434c7e05d53");
                _combobox1148Info = new RepoItemInfo(this, "ComboBox1148", "combobox[@controlid='1148']", 30000, null, "19f5754a-9028-49ec-bf2b-f1dec49b0ef4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b98b1967-7971-4da3-b1de-e3344c618477")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b98b1967-7971-4da3-b1de-e3344c618477")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CtrlNotifySink item.
            /// </summary>
            [RepositoryItem("4a85c9d2-6cf1-437a-9f8b-adf20acba2bf")]
            public virtual Ranorex.Container CtrlNotifySink
            {
                get
                {
                    return _ctrlnotifysinkInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The CtrlNotifySink item info.
            /// </summary>
            [RepositoryItemInfo("4a85c9d2-6cf1-437a-9f8b-adf20acba2bf")]
            public virtual RepoItemInfo CtrlNotifySinkInfo
            {
                get
                {
                    return _ctrlnotifysinkInfo;
                }
            }

            /// <summary>
            /// The SomeButton item.
            /// </summary>
            [RepositoryItem("abf98f0b-88dd-4be7-b838-3b6eece5ad68")]
            public virtual Ranorex.Button SomeButton
            {
                get
                {
                    return _somebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SomeButton item info.
            /// </summary>
            [RepositoryItemInfo("abf98f0b-88dd-4be7-b838-3b6eece5ad68")]
            public virtual RepoItemInfo SomeButtonInfo
            {
                get
                {
                    return _somebuttonInfo;
                }
            }

            /// <summary>
            /// The БазаОбъектовГеология item.
            /// </summary>
            [RepositoryItem("a7b5c870-a355-430c-b8ab-d308d22e5116")]
            public virtual Ranorex.TreeItem БазаОбъектовГеология
            {
                get
                {
                    return _базаобъектовгеологияInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The БазаОбъектовГеология item info.
            /// </summary>
            [RepositoryItemInfo("a7b5c870-a355-430c-b8ab-d308d22e5116")]
            public virtual RepoItemInfo БазаОбъектовГеологияInfo
            {
                get
                {
                    return _базаобъектовгеологияInfo;
                }
            }

            /// <summary>
            /// The SomeButton1 item.
            /// </summary>
            [RepositoryItem("f14f78a9-db7c-42a1-9ebc-5e08b71589ca")]
            public virtual Ranorex.Button SomeButton1
            {
                get
                {
                    return _somebutton1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SomeButton1 item info.
            /// </summary>
            [RepositoryItemInfo("f14f78a9-db7c-42a1-9ebc-5e08b71589ca")]
            public virtual RepoItemInfo SomeButton1Info
            {
                get
                {
                    return _somebutton1Info;
                }
            }

            /// <summary>
            /// The ButtonОткрыть item.
            /// </summary>
            [RepositoryItem("5f827be2-bb58-4634-b936-efc7455f435f")]
            public virtual Ranorex.Button ButtonОткрыть
            {
                get
                {
                    return _buttonоткрытьInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonОткрыть item info.
            /// </summary>
            [RepositoryItemInfo("5f827be2-bb58-4634-b936-efc7455f435f")]
            public virtual RepoItemInfo ButtonОткрытьInfo
            {
                get
                {
                    return _buttonоткрытьInfo;
                }
            }

            /// <summary>
            /// The ToolBar1001 item.
            /// </summary>
            [RepositoryItem("58f9fe9a-d811-4845-a3d0-7434c7e05d53")]
            public virtual Ranorex.ToolBar ToolBar1001
            {
                get
                {
                    return _toolbar1001Info.CreateAdapter<Ranorex.ToolBar>(true);
                }
            }

            /// <summary>
            /// The ToolBar1001 item info.
            /// </summary>
            [RepositoryItemInfo("58f9fe9a-d811-4845-a3d0-7434c7e05d53")]
            public virtual RepoItemInfo ToolBar1001Info
            {
                get
                {
                    return _toolbar1001Info;
                }
            }

            /// <summary>
            /// The ComboBox1148 item.
            /// </summary>
            [RepositoryItem("19f5754a-9028-49ec-bf2b-f1dec49b0ef4")]
            public virtual Ranorex.ComboBox ComboBox1148
            {
                get
                {
                    return _combobox1148Info.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBox1148 item info.
            /// </summary>
            [RepositoryItemInfo("19f5754a-9028-49ec-bf2b-f1dec49b0ef4")]
            public virtual RepoItemInfo ComboBox1148Info
            {
                get
                {
                    return _combobox1148Info;
                }
            }

            /// <summary>
            /// The ShellView folder.
            /// </summary>
            [RepositoryFolder("32eddda8-58fb-4852-9a2b-fe755a201e95")]
            public virtual eadcsRepositoryFolders.ShellViewFolder ShellView
            {
                get { return _shellview; }
            }

            /// <summary>
            /// The Tree1001 folder.
            /// </summary>
            [RepositoryFolder("d1b7a235-19f6-4361-abcc-a39a0de342f3")]
            public virtual eadcsRepositoryFolders.Tree1001Folder Tree1001
            {
                get { return _tree1001; }
            }
        }

        /// <summary>
        /// The ShellViewFolder folder.
        /// </summary>
        [RepositoryFolder("32eddda8-58fb-4852-9a2b-fe755a201e95")]
        public partial class ShellViewFolder : RepoGenBaseFolder
        {
            RepoItemInfo _просмотрэлементовInfo;
            RepoItemInfo _uiimageInfo;
            RepoItemInfo _systemitemnamedisplayInfo;
            RepoItemInfo _systemitemnamedisplay1Info;
            RepoItemInfo _systemitemnamedisplay2Info;

            /// <summary>
            /// Creates a new ShellView  folder.
            /// </summary>
            public ShellViewFolder(RepoGenBaseFolder parentFolder) :
                    base("ShellView", "element[@class='DUIViewWndClassName']//container[@caption='ShellView']", parentFolder, 30000, null, false, "32eddda8-58fb-4852-9a2b-fe755a201e95", "")
            {
                _просмотрэлементовInfo = new RepoItemInfo(this, "ПросмотрЭлементов", "?/?/list[@accessiblename='Просмотр элементов']", 30000, null, "794a6930-04f1-4105-8cb5-dd34e8380515");
                _uiimageInfo = new RepoItemInfo(this, "UIImage", "?/?/listitem[@automationid='1']/picture[@classname='UIImage']", 30000, null, "2f972647-0b5f-4a61-9f7d-16e214fdaf19");
                _systemitemnamedisplayInfo = new RepoItemInfo(this, "SystemItemNameDisplay", "?/?/listitem[@automationid='1']/text[@automationid='System.ItemNameDisplay']", 30000, null, "eba7676a-c982-4c64-8d8a-6f1c6a9a80f7");
                _systemitemnamedisplay1Info = new RepoItemInfo(this, "SystemItemNameDisplay1", "?/?/listitem[@automationid='4']/text[@automationid='System.ItemNameDisplay']", 30000, null, "b2272d0b-acbe-483d-9d19-d62768d5bcee");
                _systemitemnamedisplay2Info = new RepoItemInfo(this, "SystemItemNameDisplay2", "?/?/listitem[@automationid='6']/text[@automationid='System.ItemNameDisplay']", 30000, null, "69cfaa85-4959-48b7-98cd-e42773967d68");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("32eddda8-58fb-4852-9a2b-fe755a201e95")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("32eddda8-58fb-4852-9a2b-fe755a201e95")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ПросмотрЭлементов item.
            /// </summary>
            [RepositoryItem("794a6930-04f1-4105-8cb5-dd34e8380515")]
            public virtual Ranorex.List ПросмотрЭлементов
            {
                get
                {
                    return _просмотрэлементовInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The ПросмотрЭлементов item info.
            /// </summary>
            [RepositoryItemInfo("794a6930-04f1-4105-8cb5-dd34e8380515")]
            public virtual RepoItemInfo ПросмотрЭлементовInfo
            {
                get
                {
                    return _просмотрэлементовInfo;
                }
            }

            /// <summary>
            /// The UIImage item.
            /// </summary>
            [RepositoryItem("2f972647-0b5f-4a61-9f7d-16e214fdaf19")]
            public virtual Ranorex.Picture UIImage
            {
                get
                {
                    return _uiimageInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The UIImage item info.
            /// </summary>
            [RepositoryItemInfo("2f972647-0b5f-4a61-9f7d-16e214fdaf19")]
            public virtual RepoItemInfo UIImageInfo
            {
                get
                {
                    return _uiimageInfo;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item.
            /// </summary>
            [RepositoryItem("eba7676a-c982-4c64-8d8a-6f1c6a9a80f7")]
            public virtual Ranorex.Text SystemItemNameDisplay
            {
                get
                {
                    return _systemitemnamedisplayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item info.
            /// </summary>
            [RepositoryItemInfo("eba7676a-c982-4c64-8d8a-6f1c6a9a80f7")]
            public virtual RepoItemInfo SystemItemNameDisplayInfo
            {
                get
                {
                    return _systemitemnamedisplayInfo;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay1 item.
            /// </summary>
            [RepositoryItem("b2272d0b-acbe-483d-9d19-d62768d5bcee")]
            public virtual Ranorex.Text SystemItemNameDisplay1
            {
                get
                {
                    return _systemitemnamedisplay1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay1 item info.
            /// </summary>
            [RepositoryItemInfo("b2272d0b-acbe-483d-9d19-d62768d5bcee")]
            public virtual RepoItemInfo SystemItemNameDisplay1Info
            {
                get
                {
                    return _systemitemnamedisplay1Info;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay2 item.
            /// </summary>
            [RepositoryItem("69cfaa85-4959-48b7-98cd-e42773967d68")]
            public virtual Ranorex.Text SystemItemNameDisplay2
            {
                get
                {
                    return _systemitemnamedisplay2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay2 item info.
            /// </summary>
            [RepositoryItemInfo("69cfaa85-4959-48b7-98cd-e42773967d68")]
            public virtual RepoItemInfo SystemItemNameDisplay2Info
            {
                get
                {
                    return _systemitemnamedisplay2Info;
                }
            }
        }

        /// <summary>
        /// The Tree1001Folder folder.
        /// </summary>
        [RepositoryFolder("d1b7a235-19f6-4361-abcc-a39a0de342f3")]
        public partial class Tree1001Folder : RepoGenBaseFolder
        {
            RepoItemInfo _tree100Info;
            RepoItemInfo _локальныйдискdInfo;
            RepoItemInfo _базаобъектовогр7ипгр7Info;
            RepoItemInfo _этоткомпьютерInfo;

            /// <summary>
            /// Creates a new Tree1001  folder.
            /// </summary>
            public Tree1001Folder(RepoGenBaseFolder parentFolder) :
                    base("Tree1001", "element[@class='DUIViewWndClassName']/container/element[2]/?/?/tree[@controlid='100']", parentFolder, 30000, null, false, "d1b7a235-19f6-4361-abcc-a39a0de342f3", "")
            {
                _tree100Info = new RepoItemInfo(this, "Tree100", "", 30000, null, "f0dc27d2-827e-4be4-80f8-445199257921");
                _локальныйдискdInfo = new RepoItemInfo(this, "ЛокальныйДискD", ".//treeitem[@text='Локальный диск (D:)']", 30000, null, "fba5b5ff-9ffc-4de9-ac3c-d96b940f5ba6");
                _базаобъектовогр7ипгр7Info = new RepoItemInfo(this, "БазаОбъектовОГР7ИПГР7", ".//treeitem[@text='Локальный диск (D:)']/?/?/treeitem[@text~'^База\\ объектов\\ ОГР\\ 7\\ и\\ ПГР']", 30000, null, "481eb37a-4924-469c-a2c6-536b6eb5524f");
                _этоткомпьютерInfo = new RepoItemInfo(this, "ЭтотКомпьютер", "?/?/treeitem[@text='Этот компьютер']", 30000, null, "d0b970ee-af37-444b-856d-97123ac11242");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d1b7a235-19f6-4361-abcc-a39a0de342f3")]
            public virtual Ranorex.Tree Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d1b7a235-19f6-4361-abcc-a39a0de342f3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tree100 item.
            /// </summary>
            [RepositoryItem("f0dc27d2-827e-4be4-80f8-445199257921")]
            public virtual Ranorex.Tree Tree100
            {
                get
                {
                    return _tree100Info.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The Tree100 item info.
            /// </summary>
            [RepositoryItemInfo("f0dc27d2-827e-4be4-80f8-445199257921")]
            public virtual RepoItemInfo Tree100Info
            {
                get
                {
                    return _tree100Info;
                }
            }

            /// <summary>
            /// The ЛокальныйДискD item.
            /// </summary>
            [RepositoryItem("fba5b5ff-9ffc-4de9-ac3c-d96b940f5ba6")]
            public virtual Ranorex.TreeItem ЛокальныйДискD
            {
                get
                {
                    return _локальныйдискdInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The ЛокальныйДискD item info.
            /// </summary>
            [RepositoryItemInfo("fba5b5ff-9ffc-4de9-ac3c-d96b940f5ba6")]
            public virtual RepoItemInfo ЛокальныйДискDInfo
            {
                get
                {
                    return _локальныйдискdInfo;
                }
            }

            /// <summary>
            /// The БазаОбъектовОГР7ИПГР7 item.
            /// </summary>
            [RepositoryItem("481eb37a-4924-469c-a2c6-536b6eb5524f")]
            public virtual Ranorex.TreeItem БазаОбъектовОГР7ИПГР7
            {
                get
                {
                    return _базаобъектовогр7ипгр7Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The БазаОбъектовОГР7ИПГР7 item info.
            /// </summary>
            [RepositoryItemInfo("481eb37a-4924-469c-a2c6-536b6eb5524f")]
            public virtual RepoItemInfo БазаОбъектовОГР7ИПГР7Info
            {
                get
                {
                    return _базаобъектовогр7ипгр7Info;
                }
            }

            /// <summary>
            /// The ЭтотКомпьютер item.
            /// </summary>
            [RepositoryItem("d0b970ee-af37-444b-856d-97123ac11242")]
            public virtual Ranorex.TreeItem ЭтотКомпьютер
            {
                get
                {
                    return _этоткомпьютерInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The ЭтотКомпьютер item info.
            /// </summary>
            [RepositoryItemInfo("d0b970ee-af37-444b-856d-97123ac11242")]
            public virtual RepoItemInfo ЭтотКомпьютерInfo
            {
                get
                {
                    return _этоткомпьютерInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("2f740ed7-ad26-4e0c-954c-49953e0f76c3")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _файлыautocad2004dxfasteriskdxfInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "2f740ed7-ad26-4e0c-954c-49953e0f76c3", "")
            {
                _файлыautocad2004dxfasteriskdxfInfo = new RepoItemInfo(this, "ФайлыAutoCAD2004DXFAsteriskDxf", "listitem[@text~'^Файлы\\ AutoCAD\\ 2004\\ DXF\\ \\(\\*']", 30000, null, "534952bb-b532-46b8-a1eb-ea46f327ee42");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2f740ed7-ad26-4e0c-954c-49953e0f76c3")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2f740ed7-ad26-4e0c-954c-49953e0f76c3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ФайлыAutoCAD2004DXFAsteriskDxf item.
            /// </summary>
            [RepositoryItem("534952bb-b532-46b8-a1eb-ea46f327ee42")]
            public virtual Ranorex.ListItem ФайлыAutoCAD2004DXFAsteriskDxf
            {
                get
                {
                    return _файлыautocad2004dxfasteriskdxfInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ФайлыAutoCAD2004DXFAsteriskDxf item info.
            /// </summary>
            [RepositoryItemInfo("534952bb-b532-46b8-a1eb-ea46f327ee42")]
            public virtual RepoItemInfo ФайлыAutoCAD2004DXFAsteriskDxfInfo
            {
                get
                {
                    return _файлыautocad2004dxfasteriskdxfInfo;
                }
            }
        }

        /// <summary>
        /// The GEOTECH3D3AppFolder folder.
        /// </summary>
        [RepositoryFolder("2a82268b-85f0-45af-8248-1e95388ac608")]
        public partial class GEOTECH3D3AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _геодезическиеInfo;
            RepoItemInfo _импортInfo;

            /// <summary>
            /// Creates a new GEOTECH3D3  folder.
            /// </summary>
            public GEOTECH3D3AppFolder(RepoGenBaseFolder parentFolder) :
                    base("GEOTECH3D3", "/form[@name='ImportDXFOption']", parentFolder, 30000, null, true, "2a82268b-85f0-45af-8248-1e95388ac608", "")
            {
                _геодезическиеInfo = new RepoItemInfo(this, "Геодезические", "?/?/radiobutton[@name='rbGeod']", 30000, null, "671653d5-c499-4f53-b4d5-538715f856ba");
                _импортInfo = new RepoItemInfo(this, "Импорт", "button[@name='btnOK']", 30000, null, "295510dc-0b66-46de-9e98-60fe721c053b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2a82268b-85f0-45af-8248-1e95388ac608")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2a82268b-85f0-45af-8248-1e95388ac608")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Геодезические item.
            /// </summary>
            [RepositoryItem("671653d5-c499-4f53-b4d5-538715f856ba")]
            public virtual Ranorex.RadioButton Геодезические
            {
                get
                {
                    return _геодезическиеInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The Геодезические item info.
            /// </summary>
            [RepositoryItemInfo("671653d5-c499-4f53-b4d5-538715f856ba")]
            public virtual RepoItemInfo ГеодезическиеInfo
            {
                get
                {
                    return _геодезическиеInfo;
                }
            }

            /// <summary>
            /// The Импорт item.
            /// </summary>
            [RepositoryItem("295510dc-0b66-46de-9e98-60fe721c053b")]
            public virtual Ranorex.Button Импорт
            {
                get
                {
                    return _импортInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Импорт item info.
            /// </summary>
            [RepositoryItemInfo("295510dc-0b66-46de-9e98-60fe721c053b")]
            public virtual RepoItemInfo ИмпортInfo
            {
                get
                {
                    return _импортInfo;
                }
            }
        }

        /// <summary>
        /// The GEOTECH3D4AppFolder folder.
        /// </summary>
        [RepositoryFolder("2df0d4a1-d329-45e1-8c0d-e0359fed0d6e")]
        public partial class GEOTECH3D4AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _продолжитьInfo;

            /// <summary>
            /// Creates a new GEOTECH3D4  folder.
            /// </summary>
            public GEOTECH3D4AppFolder(RepoGenBaseFolder parentFolder) :
                    base("GEOTECH3D4", "/form[@name='frmImportDxfShift']", parentFolder, 30000, null, true, "2df0d4a1-d329-45e1-8c0d-e0359fed0d6e", "")
            {
                _продолжитьInfo = new RepoItemInfo(this, "Продолжить", "button[@name='Button1']", 30000, null, "77e2e515-86a1-4b88-93b9-fcdccbacf1ce");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2df0d4a1-d329-45e1-8c0d-e0359fed0d6e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2df0d4a1-d329-45e1-8c0d-e0359fed0d6e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Продолжить item.
            /// </summary>
            [RepositoryItem("77e2e515-86a1-4b88-93b9-fcdccbacf1ce")]
            public virtual Ranorex.Button Продолжить
            {
                get
                {
                    return _продолжитьInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Продолжить item info.
            /// </summary>
            [RepositoryItemInfo("77e2e515-86a1-4b88-93b9-fcdccbacf1ce")]
            public virtual RepoItemInfo ПродолжитьInfo
            {
                get
                {
                    return _продолжитьInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("ae76c50c-1226-4991-aa6f-d9528b9ea9d9")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _geotech3dInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "ae76c50c-1226-4991-aa6f-d9528b9ea9d9", "")
            {
                _geotech3dInfo = new RepoItemInfo(this, "GeoTech3D", "container[@controlid='40965']//toolbar[@accessiblename='Работающие приложения']/button[@accessiblename='GeoTech-3D']", 30000, null, "be68bca1-4a32-40ee-a76b-456f38ff9b68");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ae76c50c-1226-4991-aa6f-d9528b9ea9d9")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ae76c50c-1226-4991-aa6f-d9528b9ea9d9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GeoTech3D item.
            /// </summary>
            [RepositoryItem("be68bca1-4a32-40ee-a76b-456f38ff9b68")]
            public virtual Ranorex.Button GeoTech3D
            {
                get
                {
                    return _geotech3dInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The GeoTech3D item info.
            /// </summary>
            [RepositoryItemInfo("be68bca1-4a32-40ee-a76b-456f38ff9b68")]
            public virtual RepoItemInfo GeoTech3DInfo
            {
                get
                {
                    return _geotech3dInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}